### ISSUE TITLE
Temporary failure in name resolution for any external pull

### ISSUE THREAD

**Issue by supachris28** [containers/podman-desktop#1405]
### Bug description

This is a corporate environment with a locked down machine, where a number of hoops have been jumped through and I feel like I'm nearly there....

Any action requiring external data seems to fail with the same error message `Temporary failure in name resolution`

* podman run hello-world
* podman pull-hello-world
* Dockerfile build with any upstream server

I installed WSL2 (via an admin using an admin account).
I switched to my locked down account, ran `wsl --update` which installed the kernel for my user and allowed me to launch Ubuntu.
Got podman desktop installed via an admin account, initialised and started it.
Within Ubuntu I have set `/etc/resolv.conf` which allows me to ping google.com, curl google.com. I can't ping quay.io but I can curl https://quay.io

I can't rule out further interference from our corporate lockdown, but I can request changes so would appreciate any support to diagnose the issue further.

### Operating system

Windows 10 Enterprise 10.0.19042

### Version

0.11.0

### Steps to reproduce

Any podman command that requires pulling from a public container registry.

**Comment by benoitf** [comment]
@supachris28 this is when you do the pull with the CLI or when you use the pull image button from the images page on Podman Desktop ?

**Comment by supachris28** [comment]
Both have the same error message

**Comment by cdrage** [comment]
@supachris28 I just want to rule out if this has been fixed by the numerous DNS fixes that upstream `podman` has done.

Could you try with the newest version of podman desktop + podman and see if it's been resolved?

You are right though, when being setup behind WSL or even a VM, there are numerous host resolution issues. I just experienced this (again) on my M1 machine as well as on Windows 10. Although usually a restart of the podman VM managed to fix it / propagate any DNS changes, having it behind a more corporate lockdown environment means we don't have any indication where the blocking is occuring. It could be when it's trying to propagate any local host changes, or even something as simple as DNS not being added (you can manually configure podman VM to use 8.8.8.8, etc though).

**Comment by cdrage** [comment]
I'm going to temporarily remove this from the sprint planning / backlog as we haven't received a reply / unreproducible.

**Comment by supachris28** [comment]
Apologies for the lack of reply on this - I moved to using only WSL cmdline for podman. A combination of a locked down machine and DNS resolution issues between different work sites meant dropping to the simplest setup. Please feel free to close.

**Comment by cdrage** [comment]
> Apologies for the lack of reply on this - I moved to using only WSL cmdline for podman. A combination of a locked down machine and DNS resolution issues between different work sites meant dropping to the simplest setup. Please feel free to close.

No problem! If you encounter this issue again feel free to re-open. There's been numerous changes to podman and podman desktop regarding networking resolution, so it could be that the issue has been resolved.
