### ISSUE TITLE
Check/validate/refresh container engine connection

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1446]
Few users have been reporting issues with the list of containers / pods which appear to be empty while some are actually running. 

From an early analyze, we anticipate this issue due to the connection to the Podman Socket being killed and not reconnected properly.

We would like to explore building:
- check for the connection status (ping/pong)
- reconnect mechanism

**Comment by lstocchi** [comment]
I've been trying to look at it and there is still something not clear to me.

To me the problem is that we don't support multiple docker contexts and it's not a problem about ping/pong and reconnect as there are already calls with timer that gets executed in loop.

Example:
1. everything is stopped. I launch podman desktop, my podman machine gets started and opens the docker socket. I see the resources from podman. I start my docker desktop which have some containers and i don't see them within my podman desktop because it uses a different docker context and socket. I stop my podman machine and i don't see anything.

2. eveything is stopped. I launch my docker desktop and it opens the docker socket, then i launch podman desktop. I see the resources of both. If i stop one or the other i still see the resources of the running engines.

Am i missing something? @benoitf

**Comment by benoitf** [comment]
you can simulate that by using a custom socket with socat. Then you kill the socket and it'll break as we don't try to reconnect if there is no event change.

**Comment by lstocchi** [comment]
> you can simulate that by using a custom socket with socat. Then you kill the socket and it'll break as we don't try to reconnect if there is no event change.

i'm trying, still no success, but i was thinking. If i connect to a socket and it works i see the resources from my engine, then the connection gets killed somehow. Because there is no ping/pong/reconnection i don't see that i was kicked out so i don't see any changes in my dashboard (i still see what i saw when opening it), right? But the user sees an empty list from the beginning and it never changes.

It seems to me we're working on a different issue but not the one that affect the user.

**Comment by benoitf** [comment]
if there is a broken connection, you won't get new updates, correct.
And it seems a lot of people have 'refreshing' issues.

Like they pull an image (or start a container) and it is not being updated.
But we can't say to them: Is that the connection is still alive ? (as we don't display that and there is no reconnection as well if the connection is dropped so it's not possible to tell: it is not related to this problem)
