### ISSUE TITLE
Feature Documentation

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#1838]
### Is your enhancement related to a problem? Please describe

Agree on template on how to write documentation for a Feature

### Describe the solution you'd like

Clear documentation detailing how to write documentation for feature

**Comment by cdrage** [comment]
I believe we should add this to CONTRIBUTING.md which includes the correct "writing style" for us to use.

Do you have any links that would be beneficial @themr0c ? Like a "user writing guide" that we use?

**Comment by themr0c** [comment]
That's a very good question. We have a very specific "tone and voice". It is difficult to reference the  usual Red Hat guidelines (minimalism, modular docs, style guide), because they barely apply. We use some good practices, don't use others...

Basically:

Spell checking: US English.

Style guide: 

A subset of Red Hat supplementary style guide as implemented in the Vale ruleset: rules providing correcting guidance to the user, and clearly benefiting to clarity.

From minimalism:

- Start a title with a gerund.
- Imperative form for steps.
- Put steps in logical order.
- Avoid fluff, but loosely: we want a casual and conversational tone.

From modular docs:

- Use always the same strucure for procedures:
  - #### Prerequisites
  - unordered prerequisites list
  - #### Procedure
  - ordered steps list
  - #### Verification
  - ordered or unordered list (depending on accuracy)  

To avoid pages multiplication (this is very different from modular docs, and also fairly new and poorly implemented at the moment - I started thinking about this after looking at Google search console and the page views statistics):

- Alternative procedure: use "tabs" rather than a separate page or procedure.
- Avoid nested tabs.
- In pages using navigation, use snippets for clarity and readability to separate the contennt (snippet) from the presentation layer (tabs).
- Optional steps: use foldable "details" rather than separate pages / procedures.

As this is a GUI application: attempt to have one screenshot per page, when relevant.

**Comment by themr0c** [comment]
Also: we should introduce a new content type (tutorial?) different from a procedure, that would be for an end to end story. For example: Deploying a Compose application to Kubernetes. Deploying a container set to Kubernetes. In that kind of content, the procedure formal structure is not an asset.

I believe we can build upon the distinction between how-tos (our current procedures), and tutorials (a different content type, what we need to develop now). The distinction is fairly well explained there: https://diataxis.fr/tutorials-how-to/#understanding-the-distinction

The good docs project has a tutorial template that we could use, or get inspiration from: 
- https://gitlab.com/tgdp/templates/-/blob/main/tutorial/guide-tutorial.md
- https://gitlab.com/tgdp/templates/-/blob/main/tutorial/template-tutorial.md

**Comment by themr0c** [comment]
I hear also often that the "Prerequisites, Procedure, Verification, Additional resources" titles that we are using are too formal. We could rather use the good docs how-to template:

https://gitlab.com/tgdp/templates/-/blob/main/how-to/template-how-to.md?ref_type=heads
