### ISSUE TITLE
Differentiate the "Kind Container" in the list of container

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1951]
It should be possible to indicate in the list of containers that a container is actually a kind cluster

**Comment by deboer-tim** [comment]
I think this is a dup of #1899 (or maybe this can be the kind use of it).

**Comment by lstocchi** [comment]
it looks like #1899 solves this problem in a different way. Based on what i recall from the sprint planning in this PR we want to add a custom label, while it looks #1899 wants to customize the icon. So i wonder which one of the two we want to target as I think one is enough. @slemeur @benoitf

**Comment by benoitf** [comment]
in any case it's the extension that need to contribute that information (such as the icon as in https://github.com/containers/podman-desktop/issues/1899)

**Comment by deboer-tim** [comment]
This issue and issue #1899 are both for customizing the icon (to me 1899 is the general extension and this one is asking specifically to fix it for Kind), and there are two other issues (Issue #1549 and issue #2154) that deal with adding a provider label to pods.

IMHO these are separate, because in this case the Kind cluster is running in a Podman container, so that's what the label is going to show. The ask here is to make it clear that it's a "special" podman container. We'll need to use this sparingly, but it's good to highlight the difference in the container list.

**Comment by lstocchi** [comment]
Ok but then this issue is not clear at all and we should improve the explanation when creating them.
When i read the word differentiate, i get that even a simple label `kind` is enough. Different  job is to customize the icon. And this assumes that #1899 and #1525 needs to be almost done as there is no other way for an extension to register its own icon and PD re-use it atm.

Not a problem but it changes a bit the timing/planning.

**Comment by lstocchi** [comment]
closing as #3131 fixed this
