### ISSUE TITLE
Kind -  Tests

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#1957]
Testing scenarios and workflows for Kind. Over Windows, Mac and linux platforms.

**Comment by odockal** [comment]
Created first batch of resources here: https://github.com/odockal/podman-desktop-qe/commit/73b03d89a40e9a1201f9b95355382a15a438c439.

**Comment by odockal** [comment]
I have prepared main structure for kind verification here: https://github.com/odockal/podman-desktop-qe/blob/main/docs/scenarios/kind/kind-testing-scenarios.md. I would like to close this issue and prepare two others for more specific tasks in order to finish kind integration scenarios in PD. @slemeur wdyt?
