### ISSUE TITLE
Ask user to install compose binary to the system rather than adding to path

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#1974]
### Is your enhancement related to a problem? Please describe

When pressing the "compose" button, I'd like to be given the opportunity for the file to be copied over to `/usr/local/bin/`  rather than installed locally to `.local`

### Describe the solution you'd like

Option to install system-wide.

**Comment by fc7** [comment]
I second this, but `/usr/local/bin` or `$HOME/bin` would be preferable IMO. After pressing the "compose" button I had no idea where the binary had been installed and whether it is included in the PATH (it was not). Finally I located it with `find` under `.local/share/containers/podman-desktop//extensions-storage/compose/bin/docker-compose`. In my opinion it would be enough to inform the user where the binary was installed, and suggest the command to add that location to one's PATH, instead of installing system-wide.

BTW this new feature is not yet documented as far as I can see.

**Comment by benoitf** [comment]
updated the desc
I thought that clicking on the compose icon is displaying where it downloaded the file

**Comment by benoitf** [comment]
User should be prompted to do a system wide installation (accept or reject or select an alternate path)

**Comment by davdr** [comment]
> I thought that clicking on the compose icon is displaying where it downloaded the file

FYI on Windows this path isn't displayed
