### ISSUE TITLE
Support for Mac OS 10.15+ (Intel)

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2]
## Description ##
The solution should be available to mac users starting with OSX 10.15 or newer.
(For Mac with Intel chip)

## Acceptance criteria ##

- Container Desktop is starting on OSX 10.15+ and all its components (tray and dashboard) are properly integrated:
  - The tray is properly integrated in the mac toolbar
  - The dashboard is running as an application natively integrated
- CI is setup, configured to test the tool on the target OS

**Comment by rhatdan** [comment]
Why Mac for Intel Chip?  What about M1?

**Comment by baude** [comment]
why is this an issue?

**Comment by gbraad** [comment]
@rhatdan i think the description is about the desktop tooling and not the container runtimes

For example

> OS 10.15 ?

for CRC we are in the process to soon deprecate 10.15 and only allow the use of macOS 11 due to the virtualization stack. Is this a strict requirement?

However this should not prevent a tool to allow use on older environment using an extension that uses a remote instance of a container runtime or cluster.

> Intel

Targeting Intel is probably not ideal, as even for CI purpose it is near to impossible to acquire Intel hardware. CircleCI still does, but for how long? Generic solution is possible, so no need to target Intel specifically, unless it is a boundary to simplify. 

@rhatdan does Podman not directly target Intel or support as platform at moment?

**Comment by slemeur** [comment]
@rhatdan : Mac with Silicon (Apple) chip will be handle with in a different issue https://github.com/containers/desktop/issues/4.

**Comment by benoitf** [comment]
binary provided for mac Intel and mac M1(arm64)
