### ISSUE TITLE
Kind: Cluster running out of memory, Podman Machine default is 2GB. Increase to 6GB.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#2145]
### Bug description

I keep running into this issue: https://kind.sigs.k8s.io/docs/user/known-issues/#failure-to-build-node-image when running Kind.

I totally forgot that the default for podman machine is set to 2GB.

We should the default for Podman Machine to 6GB so users don't unexpectedly run into this issue.

### Operating system

M1

### Version

0.14.1

### Steps to reproduce

Try to run `kind` / create a cluster with only 2GB of RAM set in Podman Machine.

**Comment by deboer-tim** [comment]
I am running multiple Kind clusters with only 2GB, so this is likely only hit when building or being a bit more active.

Raising the default a bit makes sense, but users may have existing Podman machines with less, have created machines from the cli, or want to start with less because they aren't using Kind yet. Some may be annoyed that 'podman needs too much memory' while we're raising it to try to cover all possible uses. Net: there is probably a quick-fix to raise the default, but we probably need at least other issue to cover what to do if the user tries to use an existing machine (block or offer to increase memory?), are maybe some guidance during machine creation.

**Comment by cdrage** [comment]
> I am running multiple Kind clusters with only 2GB, so this is likely only hit when building or being a bit more active.
> 
> Raising the default a bit makes sense, but users may have existing Podman machines with less, have created machines from the cli, or want to start with less because they aren't using Kind yet. Some may be annoyed that 'podman needs too much memory' while we're raising it to try to cover all possible uses. Net: there is probably a quick-fix to raise the default, but we probably need at least other issue to cover what to do if the user tries to use an existing machine (block or offer to increase memory?), are maybe some guidance during machine creation.

Yeah, the limit is hit from running Ingress controllers as both Contour and NGINX controllers both request way more GB.

We can try warning the user when initially deploying Kind to perhaps raise the limit before proceeding?

**Comment by deboer-tim** [comment]
Yes, I definitely think we should have that warning, whether or not we raise the default.
