### ISSUE TITLE
Differentiate the provider on where the Pods are running

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2154]
In the list of containers, it is possible to differentiate in which provider the container is running.

On the list of pods, I should be able to know where the pod is running:
- Locally with Podman
- On my Kubernetes context

We should be able to provide a pretty name for:
- Kind running locally
- OpenShift Local
- Devsanbox

**Comment by deboer-tim** [comment]
A lot of overlap with issue #1549, just dropping a link so that the connection isn't lost.

**Comment by deboer-tim** [comment]
I took a quick look at this, and my first thought was that I have multiple kind clusters, so I also want to know _which_ kind cluster. A change to use the name of the cluster as the label is actually really simple, and since the user is picking the name of kind clusters they tend to be short and obvious names... but the cluster names in the case of others like OpenShift Local and Sandbox tend to be long and ugly.

I think the best solution is likely to be the cluster name, with some way to let extensions provide a shorter/friendly name for the ones they control. Not sure if the initial fix is worth doing in the meantime because it'll improve the differentiation at the expense of usability for now.
