### ISSUE TITLE
Propagate the state of actions from Dashboard (Start Podman -> Podman starting) to the Resources

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2181]
### Is your enhancement related to a problem? Please describe

When I press "Start Podman" in Dashboard page, when on Mac it takes quite a time to actually start podman, So I see "Podman starting". I am impatient and so I go to Settings -> Resources, but there I is not progress or whatsoever indicating that the action is ongoing. 

### Describe the solution you'd like

It would be nice to see progress circle (turning wheel or how is it called) on start button in podman machine in Resources when it is initiated from different location (dashboard).

**Comment by deboer-tim** [comment]
IMHO this is because we're too fancy at the renderer level with in-progress/interim states, would prefer to move this state more to main or at least the stores so that all clients get the same view. I slowly switched to this approach for extensions: https://github.com/containers/podman-desktop/pull/2190
