### ISSUE TITLE
Podman Desktop does not display running containers

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2310]
### Bug description

I'm running a docker compose file with podman. The containers are not displayed in the UI, while I have many of them up and running.

### Operating system

Ventura 13.2

### Version

next (development version)

### Steps to reproduce

Create a machine with sufficient resources:
<img width="526" alt="Capture d’écran 2023-05-02 à 17 21 14" src="https://user-images.githubusercontent.com/1636769/235710988-1fc666f0-aee7-4ede-9f3f-92c21bae9bb3.png">

Run docker compose up on https://github.com/redis-developer/redis-microservices-ecommerce-solutions

Result:
<img width="2304" alt="Capture d’écran 2023-05-02 à 17 12 32" src="https://user-images.githubusercontent.com/1636769/235711221-59398d10-2dd3-404c-9655-4fd539cc9042.png">

**Comment by mairin** [comment]
I can reproduce this relatively reliably building main in Linux with nothing but the native OS podman... 

output of curl --silent --unix-socket /run/user/1000/podman/podman.sock "http://v1.41/containers/json?all=true" | jq . 
https://gist.github.com/mairin/515b57a2fe62e34989988909aaf2bf2f

entry from syslog around the time it happened:
https://gist.github.com/mairin/40f570776903759222d8481e64e460ca

i can reproduce from current main pretty reliably... when i tried to run that curl command while it was in the "no containers" state.... the command just hung until the containers appeared in the UI, then the curl command completed.

note i am on podman 4.5.... and this started happening around the time i upgraded to it.

**Comment by benoitf** [comment]
so probably a lock issue on podman engine but we also do a lot of requests to update the states
might be related to https://github.com/containers/podman-desktop/issues/2259 also


it might be interesting to grab the lock of podman

@mairin could you send the `SIGABRT` signal to the podman process when it hangs

**Comment by mairin** [comment]
@benoitf i tried it just now... it doesn't seem to die? but it's not coming back either. like it's hung with no containers appearing for a solid 5 min now.... see

![Screenshot from 2023-05-03 10-26-47](https://user-images.githubusercontent.com/799683/235946173-e83d1299-e1ca-4fa1-8cab-344bf538a989.png)

**Comment by benoitf** [comment]
@mairin do you have the log file of where podman (not podman desktop) displayed the dump ?

**Comment by mairin** [comment]
@benoitf I got this from syslog, is there another place that would have more detailed logs?
https://gist.github.com/mairin/4dec969ff469810405f797631f3ba938

**Comment by mairin** [comment]
it doesnt seem to put anything into syslog when it's hung and then also after i kill it

![Screenshot from 2023-05-03 10-52-49](https://user-images.githubusercontent.com/799683/235953704-232f0cfc-2b0c-4b5f-ae23-4499774be677.png)

**Comment by mairin** [comment]
This is the output when running podman in debug mode then sending SIGABRT

https://gist.github.com/mairin/186b1d967744185598608b6bc4c5e71c

**Comment by mairin** [comment]
@baude and I had a long debugging session on this today. No answers but here is what we found:

- I was reproducing reliably (every run) both with the latest flatpak built today) and using yarn watch.
- Running the latest flatpak (0.14), we could not reproduce the issue on the same system with the same set of containers,etc.
- Podman's output and syslog didn't produce anything of help / use around the situation ( 
- Brent built podman on the system with additional debugging turned on, still no useful info
- Brent downgraded the system to podman 4.4, and I could still reproduce with podman 4.4
- Brent cleaned out my containers/images and set up just a few (2 containers, 1 image) and we could not reproduce either on podman 4.4 or podman 4.5.

Something Brent observed:
- When podman first runs (whether its flatpak or building with yarn), it's running /usr/bin/podman itself, *even when the podman service is already running and available on the system*. This is probably why our debug output wasn't providing any info... because it wasn't connecting to the system podman we'd set up with debugging... not sure if this is intentional or not, but probably something worth looking at.

Brent's theory right now, is that when Podman Desktop first hits podman, it's requesting a lot, and it's triggering podman system df which is very expensive, it walks entire images to calculate size... So the question is, between Podman Desktop 0.14 and recent merged changes, did something change about what we request of podman at startup wrt to image size or size calculations generally?

Since I have a solid method of reproducing, I'm going to walk back through each nightly flatpak and see at which version I can no longer reproduce, which might help narrow down what (if any) changes to podman desktop triggered this.

**Comment by mairin** [comment]
Note: Fedora 38, podman v4.5.

I ended up trying `git bisect` with `yarn watch` which didn't go so well bc I couldn´t find a good version. Turns out I can reproduce all the way back to v0.11.0. I can't run v0.10.0 or older, it gives me an initializing screen that it doesnt get past so the UI never loads. To make sure this isn't a yarn thing, I ran the v0.11.0 flatpak and was also able to reproduce using that. 🤷🏻‍♀️ I also installed podman 4.3 on the system, removing 4.5, running 4.3 via systemd, and tried both a yarn build from main and running the v0.11.0 flatpak with 4.3... was able to reproduce with both.

**Comment by jeffmaury** [comment]
Not sure this is related to Podman Desktop as I can reproduce using the CLI I can see `podman ps` being really slow to answer

**Comment by mairin** [comment]
@jeffmaury Yeh, we were seeing a pretty consistent 7s delay using curl, it seemed to be stuck in `podman system df`. But it is puzzling how the delay is reproducible in podman 4.3, 4.4, 4.5 but the issue in Podman Desktop has only been noticeable in recent days?

**Comment by mairin** [comment]
Is spawning a new podman service instead of connecting to the pre-existing one a new Podman Desktop behavior that might explain the change? Like, the podman delay might be exacerbated by having a new podman start up and conflict with an already-running one? (I did see write errors in syslog which I assume is one podman unable to write to the same socket bc the other podman was doing so?)

**Comment by jeffmaury** [comment]
Or maybe the Podman socket service being slower to start

**Comment by mairin** [comment]
Here's my reproducer steps... note depending on how beefy your system/vm is, penpot is enough to trigger it, but adding ChRIS helps a lot :-) 

1. Install F38, make sure under Software Selection you pick a desktop for the base, i used cinnamon since i had the notion it is smaller than GNOME. I used virt manager and this iso: 
2. Install flatpak + git + podman-compose; `sudo dnf install flatpak git podman-compose -y`
3. Install flathub; `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
4. Install Podman Desktop; `flatpak install flathub io.podman_desktop.PodmanDesktop`
5. Install sample apps:
   - Penpot: 
      a. `git clone https://github.com/penpot/penpot.git`
      b. `cd penpot/docker/images; podman-compose -p penpot -f docker-compose.yaml up -d`
      c. (when prompted, choose docker hub images)
   - miniChRIS
      a. `cd; git clone https://github.com/FNNDSC/miniChRIS-podman-compose.git`
      b. `cd miniChRIS-podman-compose; ./minichris.sh`
6. Run podman desktop: `flatpak run io.podman_desktop.PodmanDesktop `
7. Click on the cube icon (The containers tab on the left)... when it loads you'll see a message that you have no container engine even though you do. Wait some seconds and the containers will finally appear.


To build Podman Desktop instead of run a flatpak:

1. `cd; git clone https://github.com/containers/podman-desktop.git`
2. `cd podman-desktop; yarn install`

Every time you want to build you do
`yarn; yarn watch`

**Comment by mairin** [comment]
Couple of things to note:

Here is where Podman Desktop spawns a new podman process on Linux:
https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/extension.ts#L620-L629

Here is where Podman Desktop calls df:
https://github.com/containers/podman-desktop/blob/main/packages/main/src/plugin/container-registry.ts#L430

Suggested additional logging from @benoitf :

```
const startTime = performance.now();
const storageDefinition = await provider.api.df();
const endTime = performance.now();
console.log(`Took ${endTime - startTime} to do df() call`);
```

**Comment by mairin** [comment]
@baude has a podman binary that spits out the timings for the calls Podman Desktop makes to podman, see below results from my system 😬 I basically just have Penpot and ChRIS set up.

```
------> GET CONTAINERS:  1     85.96893ms
---------> GET IMAGES:  1     121.70195ms
---------> GET IMAGES:  2     324.095018ms
---------> GET IMAGES:  3     383.413735ms
---------> GET IMAGES:  4     360.207454ms
---------> GET IMAGES:  5     343.790929ms
---------> GET IMAGES:  6     386.771358ms
---------> GET IMAGES:  7     397.918316ms
---------> GET IMAGES:  8     363.565766ms
---------> GET IMAGES:  9     443.791217ms
---------> GET IMAGES:  10     379.855447ms
------> GET CONTAINERS:  2     591.24169ms
------> GET CONTAINERS:  3     593.283931ms
--> GET DISK DF:  1    9.639635477s <<==========
--> GET DISK DF:  2    9.613430025s <<==========
--> GET DISK DF:  3    9.99098829s <<==========
--> GET DISK DF:  4    10.27480914s <<==========
--> GET DISK DF:  5    10.553699587s <<==========
--> GET DISK DF:  6    10.861637927s <<==========
--> GET DISK DF:  7    11.091748847s <<==========
------> GET CONTAINERS:  4     1.372766186s
--> GET DISK DF:  8    11.360966592s <<==========
------> GET CONTAINERS:  5     973.161152ms
------> GET CONTAINERS:  6     708.559956ms
------> GET CONTAINERS:  7     1.918242086s
------> GET CONTAINERS:  8     217.591712ms
------> GET CONTAINERS:  9     2.131765279s
--> GET DISK DF:  9    11.615330457s <<==========
------> GET CONTAINERS:  10     1.467454335s
------> GET CONTAINERS:  11     171.900328ms
------> GET CONTAINERS:  12     647.06869ms
--> GET DISK DF:  10    11.808115568s <<==========
------> GET CONTAINERS:  13     101.261811ms
------> GET CONTAINERS:  14     116.507508ms
------> GET CONTAINERS:  15     114.13592ms
------> GET CONTAINERS:  16     103.913788ms
------> GET CONTAINERS:  17     126.897242ms
------> GET CONTAINERS:  18     146.919378ms
------> GET CONTAINERS:  19     148.395554ms
------> GET CONTAINERS:  20     157.164291ms
------> GET CONTAINERS:  21     159.507041ms
------> GET CONTAINERS:  22     166.031689ms
------> GET CONTAINERS:  23     165.22101ms
------> GET CONTAINERS:  24     170.369012ms
------> GET CONTAINERS:  25     172.339687ms
```

**Comment by mairin** [comment]
Quick update: @benoitf made some changes we tested yesterday that include timings on the Podman Desktop side. The containers, pods, and images load much more quickly with this version on a system/configuration that previously was reproducing visible delays of up to 30s. Volumes still has a delay but could be lazy loaded.

Branch for the changes:
https://github.com/containers/podman-desktop/tree/DESKTOP-2375

Test output from yesterday (left side is @baude 's podman binary with timings, right side is Podman Desktop timing output):
![Screenshot from 2023-05-09 17-25-29](https://github.com/containers/podman-desktop/assets/799683/66173801-2ac2-4df1-80dc-c3ab105a6437)

**Comment by baude** [comment]
Great news
