### ISSUE TITLE
Most screens are not properly resizing when adjusting the width of the application

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#2322]
### Bug description

Most screens are not properly resizing when adjusting the width of the application
- List of images
- Settings
- Details of images
- List of containers
- Details of containers
- ...

https://user-images.githubusercontent.com/1636769/235879279-7c211a15-bbb9-4fe8-ba6c-b65ca0d249e1.mp4

### Operating system

Ventura 13.3.1

### Version

next (development version)

**Comment by lstocchi** [comment]
@slemeur can you please verify if you still face any issue using the main? #2323 has been merged and it should cover this issue as well

**Comment by slemeur** [comment]
Just tested. I think this is "fixed" in the sense that the horizontal sliders are now displayed back. But still feels that the UI does not adapt very well to small width setting

**Comment by slemeur** [comment]
pushing out of 237

**Comment by deboer-tim** [comment]
Likely fixed by PR #2863, will confirm.

**Comment by deboer-tim** [comment]
Found one minor issue with Image list, fixed by PR #2918. The only remaining issue I can find is that the details pages do not handle very narrow sizing:

<img width="607" alt="Screenshot 2023-06-19 at 8 46 09 AM" src="https://github.com/containers/podman-desktop/assets/19958075/5ad93c39-bd36-4570-900c-06488fdd8239">

This will require a change in the layout of all the pages, this issue should stay open to track that.
