### ISSUE TITLE
Forms should set focus to first input field after opening where appropriate

### ISSUE THREAD

**Issue by dgolovin** [containers/podman-desktop#2495]
### Is your enhancement related to a problem? Please describe

In `Create New Resource` and `Pull Image from a Registry` forms first text field has no focus after opening and that requires extra click before one starts typing to fill it up.

### Describe the solution you'd like

As a user I want to open a form and should be able to start filling it up without extra click.

**Comment by benoitf** [comment]
related to https://github.com/containers/podman-desktop/issues/1184#issuecomment-1384535668

**Comment by deboer-tim** [comment]
Changing the focus unexpectedly is definitely bad, but when you're (e.g.) opening a form it feels natural to me to put the cursor in the first input.

There is a a11y warning if you try to do this in the <input>, but I saw examples of using Svelte onMount() to avoid it. I tried this on pull image and it does feel better.

@mairin is there a standard to follow here?

**Comment by mairin** [comment]
@deboer-tim as with a lot of things UX it depends on context :) So the reason you might get an a11y warning if you have autofocus on the first form field, is that autofocus doesn't just impact input but it impacts where the screen reader starts rading. So if you have text that appears before the form field that gets autofocused (e.g. a description of the form or even the form title), it will cause the screenreaders to skip past that text. It's annoying for screen reader users, because they have to then manually skip the screen reader back to understand where they even are.

(This kind of describes the experience: https://brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/ note it's from 2009!) 

For Create New Resource, say you're creating a new Developer Sandbox - there's intro text there you'd might want to read before jumping to input, so this might not be a good option for this screen (unless maybe we could shove it into an aria property for the input field?):

![Screenshot from 2023-05-16 14-55-41](https://github.com/containers/podman-desktop/assets/799683/1c3d237f-699a-45e1-941f-acd040c7f45b)

For Pull Image From a Registry - The issue with this one is the manage registries / login to a registry buttons on the top - you'd skip past those. Otherwise, this one would probably be fine to set autofocus with HTML5, bc the form field has a label and the button they clicked on to get there "Pull image" has some context, although, i would say the button says "Pull image" not "Pull image from registry" (it's implied) so I think it would help if the form field had some default text besides "Image name" that gave the context that can include the registry URL (i know it doesn't need the registry URL, but you could do either)

![Screenshot from 2023-05-16 15-07-45](https://github.com/containers/podman-desktop/assets/799683/4277d628-eb78-423f-a040-03ed0cb54e57)


We might need to rethink the layouts of the pull from registry screen before applying this. Screen readers go by the DOM order not the visual order, so maybe something clever can be done with the button positions.

Generally, another way we could make filling forms a bit nicer and involve less mouse / keyboard transfer would be to make sure we have hotkeys for each form field and button.
