### ISSUE TITLE
Disable scroll beyond last line in editors

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#2511]
### Is your enhancement related to a problem? Please describe

This isn't a super high priority and the change is very simple, but opening b/c it was top of mind and may be contentious.

On pages like deploying pods to Kubernetes the generated Kube is usually more than a page long. I often automatically scan it by scrolling down rapidly and end up with this, where it has entirely scrolled up off-screen:

<img width="416" alt="Screenshot 2023-05-16 at 11 12 04 AM" src="https://github.com/containers/podman-desktop/assets/19958075/82912b7b-4c4c-4f1a-a374-d7b5de19d715">

This is annoying b/c you think there's more and then you suddenly end up with a blank page. Even a file that's 1 line too big will have a scroll bar that makes it look like 2 pages high.

### Describe the solution you'd like

This has been annoying me in VS Code too, and I found out today that there's a 'scroll beyond last line' setting that you can disable, and a corresponding Monaco setting `scrollBeyondLastLine:false` that we can easily use. Ideally I'd prefer if you could set it to a low number of lines instead, but I found a request for this that didn't receive enough votes and was rejected by VS Code.

IMHO this default setting might make sense for some users while editing, but since we don't edit within Podman Desktop it makes sense to change this for all editor windows. (e.g. including container/pod details Inspect and Kube pages)

**Comment by mairin** [comment]
This makes sense to me, it removes the possibility of befuddling wayfinding busywork that would happen if you got lost in the extra padding beyond the bottom of the content. This isn't an editor but a viewer; if you're reading through content you're generally going to sweep your eyes from top to bottom and not rely on scroll to optimally position to content for reading (since your gaze is moving downward anyway.) So from a UX POV I don't have any major concerns with this, seems a net positive to remove a possibility of users getting lost in scrolling beyond content.
