### ISSUE TITLE
There should not be a "Create New ..." option for podman in Settings/Resources when podman is not installed

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#2553]
### Bug description

Create new podman machine is available even though podman is not yet installed. 

![pd-createpodman-withoutpodman](https://github.com/containers/podman-desktop/assets/19164299/3f5cc37c-135e-4c26-b875-5f0c71379b2c)

### Operating system

Windows 10

### Version

1.0.0

**Comment by KyeRussell** [comment]
I just installed Podman for the first time. On the first-run screen, whilst the main 'go to dashboard' (or whatever) button was more prominent, the 'first' CTA was to go to settings to configure which runtimes I wanted to use. I had not first been asked to install Podman, because I hadn't seen the dashboard screen yet.

**Comment by ed-randall-blk** [comment]
Ideally the podman-desktop install would lead one through the podman install if it wasn't found. The error is just plain confusing:

Error: Error: spawn podman ENOENT
