### ISSUE TITLE
Improve visibility for container engine status (add engine statuses to status bar?)

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2589]
### Is your enhancement related to a problem? Please describe

If you have a podman or other container engine starting, but not yet started, when you go to the containers or pods tabs, you get the empty list message that says "No container engine." But you do have an engine - it's just still in the process of starting. The empty list message doesn't give any hint this might be the situation, you have to go into Settings > resources to see the status of the starting engine or to the task manager messages.

### Describe the solution you'd like

It might be nice since the presence of a running container engine is essential to doing almost anything in the UI, to have the installed / active container engines listed in the bottom in the status bar with a status indication (eg running, starting, stopped, stopping, whatever the API gives us) that's present no matter what screen you are on. 

### Additional context

This was one of the original status bar mockups that showed an idea for this: 
![Screenshot from 2023-05-22 10-40-18](https://github.com/containers/podman-desktop/assets/799683/6be8308b-d15e-4941-aef8-272845302ac9)

The idea with this was you could turn the engines on/off by clicking the switch and the switch itself would indicate status.

**Comment by benoitf** [comment]
It looks like duplicating the tray icon ?

**Comment by mairin** [comment]
@benoitf yes, but it would be more visible. to see status in the tray icon for individual engines you would have to pull down the dropdown to see, right? this way the status is always visible, so if you hit an empty list bc the engine is restarting you'll see it's restarting. (also the tray icon is dicey on linux, it takes a hack to get any tray icons to work in gnome anyway. :-/)

**Comment by deboer-tim** [comment]
Maybe we could color/fill the icon instead of having each icon and a separate status slider? Clicking on it could just open a dropdown (or maybe drop-up? :) ) menu with the same actions as system tray.

I don't love the 'duplication' either, but:
- When I'm using an external terminal or some other tool the single status in the system tray, or its dropdown menu is handy to see state, start/stop without opening the dashboard.
- When I'm in Podman Desktop, the system tray is far enough away that I go to Settings to see what's running. I agree this would be more convenient for quick actions, and I wouldn't need to open anything to see basic status.

**Comment by afbjorklund** [comment]
Not all desktops _have_ tray icons
