### ISSUE TITLE
Error: unable to connect to podman. failed to create sshClient: failed to parse identity

### ISSUE THREAD

**Issue by ksingh7** [containers/podman-desktop#271]
### Bug description

In continuation to the bug, i reported #270 , after installing podman and starting the podman machine, i am unable to run any podman commands from windows > CMD or power shell

It complains about ssh

![image](https://user-images.githubusercontent.com/9701902/177390956-71e03225-3885-4aca-9d7f-de1b88105319.png)

SSH is supposed to get created when podman machine setup is being done

### Operating system

Windows 10

### Version

next (development version)

### Steps to reproduce

- Get a windows  10 machine
- download and install podman-desktop v0.0.5
- install podman and WSL
- Wait for podman machine setup and installation is done. Here you will notice the error message (which i missed to capture)
- Start podman-machine
- run any podman command like podman images, podman ps etc

**Comment by benoitf** [comment]
I think this issue could be transfered to podman 
Cc @rhatdan @n1hility

**Comment by n1hility** [comment]
@ksingh7 Can you try running "podman machine init". Does that work for you? (Note you may need to do podman machine rm first if the default machine already exists)

**Comment by ksingh7** [comment]
- Removed podman machine
![image](https://user-images.githubusercontent.com/9701902/177514545-1e2a18b4-adc1-4aab-a1f9-cb4d899ccc97.png)

- Recreated podman machine `podman machine init`
- This time SSH key got successfully created. SSH key generation failed during the first time. Is this a  known issues @n1hility 
![image](https://user-images.githubusercontent.com/9701902/177514948-144b3d45-e1de-43b8-99bf-a0e3bc254eae.png)

- Everything works after deleting the default machine and re-creating it using `podman machine init`

![image](https://user-images.githubusercontent.com/9701902/177515669-29977f86-56ca-4d62-9719-b1499ad252d9.png)


@n1hility  So the bigger question is , when we install podman-desktop for the first time and create podman machine (WSL) , SSH failed and it did not worked. Later when i removed the machine and re-created it work. How to solve this elegantly ?

**Comment by mairin** [comment]
So I had the same issue and ran thru @ksingh7 's steps above - creating an ssh key failed when I did this though. 

![Screenshot from 2022-07-06 15-31-56](https://user-images.githubusercontent.com/799683/177628566-72189c33-4323-4d7f-8f85-ab8084e97dff.png)

It fails consistently for me. :-( (E.g. if I rm podman-machine-default and try podman machine init again, it has the same ssh key issue.) 

I do have WSL installed and working (and had used podman 0.0.3 on this system with podman 4.10 before removing it and trying to install 0.0.5 with podman 4.11. The Podman Desktop prompted me to upgrade to podman 4.11 so I did the upgrade that way.) I don't understand why podman machine init is looking for a wsl.exe files in the ssh directory for my windows user?

**Comment by n1hility** [comment]
This is a bug that was fixed awhile back but is not yet in a release 
https://github.com/containers/podman/issues/14416

It's a subtle problem with the exec implementation's path resolution logic in golang when combined with the alternate directory option. The problem occurs only when podman is ran in the c:\windows\system32 directory (the location of wsl.exe). Normally a prompt opens in the user's home directory  (C:\Users\<user>), however, there are two cases where a prompt can open in system32:

1. Using the legacy CMD command prompt instead of powershell
2. Launching powershell.exe as Administrator (not through Windows Terminal)

Unfortunately, (2) happens as part of the WSL install process that podman will launch on a first-time setup when WSL has not been installed, and Windows Terminal has not been installed on the system (podman falls back to powershell.exe in this case). 

The workaround is to just change the directory to be anywhere else (e.g. cd $HOME on PS or cd %USERPROFILE% on CMD) before running machine init.

In the case of a first-time WSL install, where you don't have the ability to change the directory, you can install Windows Terminal (we recommend that anyway - winget install Microsoft.WindowsTerminal) before agreeing to launch the WSL process from podman. Or alternatively, you can manually install wsl directly first.

**Comment by n1hility** [comment]
BTW this problem has been lurking for awhile, all versions that support machine on Windows (4.0.3)+ have this bug.

**Comment by benoitf** [comment]
closing as bug is more a podman issue than podman desktop issue and it has been closed upstream https://github.com/containers/podman/issues/14416
