### ISSUE TITLE
Podman Machine AutoStarts EVEN when AutoStart button is set to Disabled

### ISSUE THREAD

**Issue by codermonkey55** [containers/podman-desktop#2781]
### Bug description

After updating Podman Desktop to 1.1.0, it tries to start the Podman Machine on every launch of Podman desktop DESPITE the "Autostart container Engine" setting being set to "Disabled/Off"

![image](https://github.com/containers/podman-desktop/assets/17110177/2b176f0d-0d39-4b6c-b59d-7a658035f9fc)

### Operating system

Windows 10 Pro 22H2

### Version

1.1.0

### Steps to reproduce

Launch Podman Desktop
Stop Podman Machine if it is running, Observe it restarts on its own.
Toggled ""Autostart container Engine" to disabled/off
Exit Podman Desktop
Re-launch Podman Desktop, observe autostarting the Podman Machine despite the setting above.

**Comment by benoitf** [comment]
hello @codermonkey55 , thanks for the report, we'll investigate

**Comment by EdwinKM** [comment]
The trigger seems podman-desktop dashboard. If i kill podman-machine in the resources screen it will stay disabled until selecting dashboard again

**Comment by tumido** [comment]
Yep, same here on Mac M1. It also triggers a start on OpenShift Local extension.

1. Launch podman desktop
2. See everything starting
3. Go to settings
4. Stop podman/openshift local
5. Switch to dashboard
6. See everything starting again

Settings:
- Autostart to "Disabled" - no effect
- Minimize on Login to "Enabled" - no effect. I can't record this on login, however Podman Desktop starts minimized (the setting itself works), though podman-machine + openshift local are starting anyways.

https://github.com/containers/podman-desktop/assets/7453394/579aac30-c68d-40a3-bae8-facc87d94f66


This is most annoying especially in the OpenShift Local case since it is a really resource-intensive workload that drains the battery fast. And if Podman Desktop starts minimized, it can go unnoticed for quite some time...
