### ISSUE TITLE
Issue pulling images from Artifactory on Windows

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#2849]
### Bug description

Reporter is using VPNkit solution, has internal docker artifactory repo. When they run podman pull image command, they get "request reading manifest error"

Reporter has confirmed they have all appropriate perms for the repo. Here is full error:

"Error: initializing source docker://<internal repo> /sl-openjdk17-openshift-custom:100258: reading manifest 100258 in openshift-docker.artifactory.na.cobank2.corp:8443/sl-openjdk17-openshift-custom: unauthorized: The client does not have permission for manifest "

Red Hat contact: bsmithley

### Operating system

Windows (Not sure which version)

### Installation Method

None

### Version

1.1.0

**Comment by cdrage** [comment]
Usually this is because of a malformed image being pushed, or a problem with the tag, it doesn't look like the log posted is the full log since it doesn't show the image tag?

Some research into the issue:
* https://github.com/containers/podman/issues/6595
* https://github.com/containers/podman/issues/5092
* https://bugzilla.redhat.com/show_bug.cgi?id=1833695

I'm also unsure how the reported has VPNkit setup so I'll have to ask for more information.

I've tried searching for bsmithley but couldn't find him, I'm going to send you a PM @mairin and go from there!

**Comment by cdrage** [comment]
As an update for this, after talking with @mairin and the customer, as well as testing this locally, it was identified that it was fixed by:

- Upgrading to 4.5.1
- Adding the insecure registry to registries.conf within the podman VM.

I am closing this issue as it will be fixed by: https://github.com/containers/podman-desktop/issues/1653 which will add documentation on how to edit registries.conf within podman to allow the pulling and pushing of an image on an insecure registry.
