### ISSUE TITLE
Clicking ESC on Create new machine/cluster, etc is not closing the window

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#2853]
### Is your enhancement related to a problem? Please describe

I would expect that using the <kbd>ESC</kbd> would close the 'Create new..." option

![image](https://github.com/containers/podman-desktop/assets/436777/1be62885-d7cb-41a9-8e7b-0761c2454d59)

### Describe the solution you'd like

<kbd>ESC</kbd>close the 'Create new..." window (as if I could hit the X icon)

**Comment by deboer-tim** [comment]
IMHO the 'proper' way to solve this would be to make this page a FormPage, because then it would also get some consistent styling in the header, and post PR #4087 all form pages would have support for Escape. The one bit I'm assuming we wouldn't want to pick up though is the background color, but would have to confirm with Mo.
