### ISSUE TITLE
Can't add registry with self signed key, even after adding certificate to podman machine

### ISSUE THREAD

**Issue by markfaine** [containers/podman-desktop#2974]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/949949/e5b6605d-fcef-4171-83d3-6b240ca3045a)

After adding the certificate as described in [Install Certificate Authority](https://github.com/containers/podman/blob/main/docs/tutorials/podman-install-certificate-authority.md), logging into the machine in WSL and pulling the container works fine but not adding the registry.  I've restarted so many times I've lost count and no matter what I do it will not recognize my organizations CA certificate.

### Operating system

Windows 10

### Installation Method

Other

### Version

1.1.0

### Steps to reproduce

 - Install the certificate as instructed
 - Attempt to add registry (gitlab in my case)

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman-desktop/issues/1653 that'll be fixed by https://github.com/containers/podman-desktop/pull/2896

**Comment by cdrage** [comment]
> 

Hey Mark!

I've been actively working on all the registry issues this month. This will be fixed with https://github.com/containers/podman-desktop/pull/2896 with the ability to actually add the registry to auth.json locally.

The second step you'll need to do however is modify `podman` to accept an insecure registry which can be found here: https://podman-desktop.io/docs/getting-started/insecure-registry

You'll be unable to do the first two steps however until https://github.com/containers/podman-desktop/pull/2896 is merged.

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/2896

**Comment by markfaine** [comment]
I can't just give it access to my CA cert?  I mean as a work around not verifying the cert is fine, but I'd rather give it access to the CA cert, or do you mean something else by 'insecure registry'?  Also Thanks!  Is this fixed now in a new release or if not is there an ETA for when this fix makes it in to the next release?
