### ISSUE TITLE
Size units wrongly processed

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#3062]
### Is your enhancement related to a problem? Please describe

When working on #3047, I noticed that size quantities (memory, disk) are specified in bytes but are not processed and displayed properly.

For example the default of Podman machine is 2GB but is specified as 2048000000 which is not exactly 2GB.
Luckily it is passed to Podman as 2048 as Podman expected MB. So far so good.

But the wizard shows a different value:

![image](https://github.com/containers/podman-desktop/assets/695993/87501822-cf4b-4737-8646-1b9b1c66bed4)

### Describe the solution you'd like

Convert properly those quantities from bytes to MB (1024 * 1024) and GB (1024 * 1024 * 1024)

**Comment by benoitf** [comment]
some related discussion there https://github.com/containers/podman-desktop/pull/2916

**Comment by afbjorklund** [comment]
MB is 1000 x 1000
MiB is 1024 x 1024

Podman uses decimal units

Some of the older code still use "M" to denote 1073741824 bytes, so there might indeed be translation errors here.

----

Like qemu:

```
       -m [size=]megs[,slots=n,maxmem=size]
           Sets guest startup RAM size to megs megabytes. Default is 128 MiB.
           Optionally, a suffix of "M" or "G" can be used to signify a value
           in megabytes or gigabytes respectively.
```

**Comment by afbjorklund** [comment]
Looks like podman passes 2048 as the value to qemu, which interprets it as MiB (even though saying "MB"!)

```C
int qemu_strtosz(const char *nptr, const char **end, uint64_t *result)
{
    return do_strtosz(nptr, end, 'B', 1024, result);
}

int qemu_strtosz_MiB(const char *nptr, const char **end, uint64_t *result)
{
    return do_strtosz(nptr, end, 'M', 1024, result);
}

int qemu_strtosz_metric(const char *nptr, const char **end, uint64_t *result)
{
    return do_strtosz(nptr, end, 'B', 1000, result);
}
```

But then when it is listed, it uses docker go-units and presents it in decimal form instead of in binary form.

```go
// CustomSize returns a human-readable approximation of a size
// using custom format.
func CustomSize(format string, size float64, base float64, _map []string) string {
        size, unit := getSizeAndUnit(size, base, _map)
        return fmt.Sprintf(format, size, unit)
}

// HumanSizeWithPrecision allows the size to be in any precision,
// instead of 4 digit precision used in units.HumanSize.
func HumanSizeWithPrecision(size float64, precision int) string {
        size, unit := getSizeAndUnit(size, 1000.0, decimapAbbrs)
        return fmt.Sprintf("%.*g%s", precision, size, unit)
}

// HumanSize returns a human-readable approximation of a size
// capped at 4 valid numbers (eg. "2.746 MB", "796 KB").
func HumanSize(size float64) string {
        return HumanSizeWithPrecision(size, 4)
}

// BytesSize returns a human-readable size in bytes, kibibytes,
// mebibytes, gibibytes, or tebibytes (eg. "44kiB", "17MiB").
func BytesSize(size float64) string {
        return CustomSize("%.4g%s", size, 1024.0, binaryAbbrs)
}
```

So the machine runs with an even 2.0 GiB memory allocated, but defaults it to 2.05 GB instead of 2.15 GB.

But then it goes ahead and tells Podman to use 2048 MiB anyway, so in the end you end up with "2.147GB"

----

For the disk size the difference is bigger, Podman has 100 GiB but Podman Desktop has 100 GB (93.13 GiB).

EDIT: Actually it got lost in translation again, so when you pass 100 GB to PD it actually tells Podman 100 GiB.

So the end result is that you end up with a qemu disk image presented in `podman machine list` as "107.4GB"

```
file format: qcow2
virtual size: 100 GiB (107374182400 bytes)
disk size: 1.54 GiB
```

**Comment by afbjorklund** [comment]
After creating a new Podman Machine with 2.048 GB memory and 100 GB disk size, you end up with 4.9-7.4% "extra":

```
NAME                    VM TYPE     CREATED         LAST UP         CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        15 minutes ago  15 minutes ago  1           2.147GB     107.4GB
```

![podman-machine-default-resources](https://github.com/containers/podman-desktop/assets/10364051/85e7dd4c-d9bc-490d-aebe-1814126038f3)

This is because the units are wrong, when it is translating the values from the sliders into the parameters:

```go
  // memory
  if (params['podman.factory.machine.memory']) {
    parameters.push('--memory');
    const memoryAsMB = +params['podman.factory.machine.memory'] / (1000 * 1000);
    parameters.push(Math.floor(memoryAsMB).toString());
  }

  // disk size
  if (params['podman.factory.machine.diskSize']) {
    parameters.push('--disk-size');
    const diskAsGB = +params['podman.factory.machine.diskSize'] / (1000 * 1000 * 1000);
    parameters.push(Math.floor(diskAsGB).toString());
  }
```

Note that it still matches the defaults of `podman machine init`, because those are: 1 CPU, 2 GiB mem, 100 GiB disk

It just uses the older standard, where we didn't have to talk about "mebibytes" but a "M" was still `1 << 20` bytes...

**Comment by benoitf** [comment]
cc @lstocchi I think you worked on the values / parsing / display of the size for machines

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman/pull/19146

**Comment by afbjorklund** [comment]
The round-off errors are worse for the disk, than for the memory:

```
NAME                    VM TYPE     CREATED       LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        1 second ago  7 minutes ago  2           3.999GB     9.664GB
```

This is because the memory is passed as MiB (4096) and not as GiB (4)

But podman only accepts integer parameters, so it cannot fit perfectly.

```
>>> 9 * 1.024 * 1.024 * 1.024
9.663676416000003
```
