### ISSUE TITLE
Broken layout when selecting a container at the bottom of the list

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3116]
### Bug description

Just look at the gif to see the behavior 
![broken_layout](https://github.com/containers/podman-desktop/assets/49404737/87f346cb-d18c-463f-85cd-85125a6ff334)

### Operating system

Windows 11

### Installation Method

None

### Version

next (development version)

### Steps to reproduce

I just scrolled down in the container list and selected the last container group

**Comment by mairin** [comment]
Just a note this is reproducible in the 1.1.0 flatpak, but we've fixed the extraneous scrollbars since so it's harder to recover from the bug now:

![Screenshot from 2023-07-11 12-14-47](https://github.com/containers/podman-desktop/assets/799683/7a712ec3-7c99-41d7-8136-6a78bd3ae89f)

^ 1.1.0, scrolled up manually a bit

**Comment by jeffmaury** [comment]
I cannot reproduce on Windows11 with a container.

**Comment by lstocchi** [comment]
@jeffmaury what if you scroll to the bottom and select the last container?

**Comment by jeffmaury** [comment]
> @jeffmaury what if you scroll to the bottom and select the last container?

Removed my comment because I was selecting the container by clicking its name but you have to select the checkbox and got it reproduced
