### ISSUE TITLE
Provide more details about the engine on the Homepage 

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#332]
### Is your enhancement related to a problem? Please describe

As a user, when I have a podman-machine that is running, I'd like to know a little bit more.

<img width="1162" alt="Capture d’écran 2022-07-21 à 14 21 08" src="https://user-images.githubusercontent.com/1636769/180212652-6185e7f5-e11c-4241-999b-4f28e5ab23cc.png">

I think it's not very clear to the user what "Podman Machine" means here and we may lack of certain quick actions.

### Describe the solution you'd like

I'd like to be able to have a dit more visual status about the podman-machine:
- For example, I'd like to know it's state but maybe be able to know how much memory/cpu is assigned to it. 
- It might be a good place, to also visually indicate there is an error. (resources or ...)
- I should be able to quickly get into the details of the machine too. 
- Maybe we should display some stats?

Also, it might be cases where users will have more than one machine. So this case may need to be handled too.

**Comment by mairin** [comment]
Since we implemented the settings > resources page with cards for each container engine / machine, there's some bits of the design to provide more machine details that we haven't implemented yet.

![Screenshot from 2023-07-05 13-03-57](https://github.com/containers/podman-desktop/assets/799683/857d2e2e-c0a1-41a8-a255-711f755cc492)

The design has this expand icon in the upper right and the idea was that clicking this icon or the name of the provider would take you to a details screen like this where you could modify the allocations to the vm, potentially get a console to the vm (eg #889), potentially provide `version` info in a tab

![Screenshot from 2023-07-05 13-02-54](https://github.com/containers/podman-desktop/assets/799683/6e0e65eb-413c-43fc-884d-9d6116018c4c)

**Comment by jeffmaury** [comment]
> Since we implemented the settings > resources page with cards for each container engine / machine, there's some bits of the design to provide more machine details that we haven't implemented yet.
> 
> ![Screenshot from 2023-07-05 13-03-57](https://user-images.githubusercontent.com/799683/251225902-857d2e2e-c0a1-41a8-a255-711f755cc492.png)
> 
> The design has this expand icon in the upper right and the idea was that clicking this icon or the name of the provider would take you to a details screen like this where you could modify the allocations to the vm, potentially get a console to the vm (eg #889), potentially provide `version` info in a tab
> 
> ![Screenshot from 2023-07-05 13-02-54](https://user-images.githubusercontent.com/799683/251226231-6e0e65eb-413c-43fc-884d-9d6116018c4c.png)

I can see a discrepancy with the create wizard as those properties are using a slider I know there is an issue with the slider as it may not be precise enough but I though we were going to keep it and add some kind of text field. So are we getting rid of sliders or do we have an issue ?

**Comment by mairin** [comment]
@jeffmaury i don't have a strong opinion on sliders vs. spinners to be honest; I think it's more important that the create and edit should be consistent. This is the older equivalent screen design (for Docker) with the sliders:

![Screenshot from 2023-07-05 13-21-24](https://github.com/containers/podman-desktop/assets/799683/b0220144-75e0-4d6e-ae64-6bdfb00c29fc)

The reason I was playing with the spin boxes instead of sliders is that it makes it less awkward / more visible what value you're choosing, and it better emulates what GNOME Boxes does. The sliders in the mockup above try to do a lot - show the active slider selection + the live resource usage to inform the selection.

I think if it's simpler to just move forward with the pre-existing sliders, we should do that!

**Comment by afbjorklund** [comment]
Since this is showing information about a running machine, it would be nice to show the server version instead of the client version - but maybe that is what is being indicated above, by talking about the "container engine" (not provider)?

`podman --version`

`podman --remote version`

For the container engine (without machine),  I guess the version information is the **only** relevant shown here ? Just showing the available CPU/mem/disk on the Linux host (and their current usage) is probably available from other sources

EDIT: It could make sense to show the _same_ information, though.

Not sure if it would need a helper binary, or how it is implemented ?
