### ISSUE TITLE
Podman-compose on windows problem (podman desktop)

### ISSUE THREAD

**Issue by samuk190** [containers/podman-desktop#3366]
### Issue Description

(podman-compose: The term 'podman-compose' is not recognized as a name of a cmdlet, function, script file, or executable)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install podman desktop
2. Activate compose extension

### Describe the results you received

Cannot use compose :(

### Describe the results you expected

be able to use compose

### podman info output

```yaml
none
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

I tried restarting pc, reinstalling it, etc, everything it doesnt work

**Comment by rhatdan** [comment]
Podman-compose is not part of the podman project, so this issue should either be moved to the podman-compose project or podman-desktop.

**Comment by daanvzijl** [comment]
I ran into the same issue due to the wording in Podman Desktop. When hovering over the compose word (bottom left in the Podman Desktop client), the following can be read: _Compose is installed and DOCKER_HOST is reachable_

It seems to suggest that compose is installed, and this might be where the confusion might be coming from.

It is however quite clear that podman-compose needs to be installed separately when looking at the guide here: https://podman-desktop.io/docs/compose/podman-compose

So maybe a change of wording in the Podman Desktop client could be of help here?

Also, I agree the issue should be moved to the podman-desktop project.

**Comment by rhatdan** [comment]
BTW We are working on a podman compose command.
