### ISSUE TITLE
Adding advanced boolean to IConfigurationPropertySchema to separates options

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#3523]
### Is your enhancement related to a problem? Please describe

When adding an option to the kind configuration https://github.com/containers/podman-desktop/pull/3508, I noticed that this option is really nice to have for a lot of people, but could confuse people to place it in the same place that the general configuration.

Adding an `Advanced` section hidden by default, and that can be shown with a "Show advanced option" switch, would allow to place the more complexe configuration option in a separate section.

### Describe the solution you'd like

In the `IConfigurationPropertySchema` we can add an option `advanced` of type `bool`.

When displaying all the options, the advanced option would be sort to be placed at the button, behind an expandable section triggered by a switch button.

Here is an example of what it could look likes for the options I specified in the other PR I quoted:

![image](https://github.com/containers/podman-desktop/assets/42176370/112380e3-ec04-4c73-ba2f-74be74caafb5)

**Comment by benoitf** [comment]
cc @mairin

**Comment by mairin** [comment]
@axel7083 Instead of using a switch, I'd use a disclosure triangle - just because "grammatically" switches aren't typically used for disclosure and it could cause confusion / unclear expectations to overload the switch widget in this way.

To help me understand the specific example here: You want to enable users to provide a custom image for kind instead of the default (which I guess is the most recent?) If so... I'd suggest some text changes. And if possible - to offer a selection instead of a copy/paste field (or at the least, a url for ppl to be able to grab links to alt images upstream. If that makes sense.)

Are you focused specifically on this one option here, or generally on providing additional advanced options?

**Comment by axel7083** [comment]
Hey @mairin, thanks for your feedback and explanation !

As we talked with @benoitf yes this features is offering the possibility to choose a custom image instead of the most recent one. (Most tools using Kubernetes usually does not support the latest version, so it is very common to use a previous version. eg: kubeflow  1.25.8) 

Offering a selection instead of copy/past is very complicated, since they are a lot of version. Kubernetes use the x.y.z, where x is the major version, y is the minor version, and z is the patch version. And they are a lot, patch can go from 0 to 16 for some version. 

The suggestion of @benoitf was to offer a selection of minor version 1.27, 1.26, etc.. and on the dropdown having a "custom" and "default (latest)" option. The custom triggering a text box to show and let the user past its own version. What do you think about this approach ? 

> Are you focused specifically on this one option here, or generally on providing additional advanced options?

I am not focused on this particular option, but use it to show how useful an advanced section could be, since some option could be very useful for more advanced users. It would probably allows more option to be put, while keeping the base interface simple.
