### ISSUE TITLE
E2E tests for verification of deleting a resources from a details pages and their redirection

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3578]
### Is your enhancement related to a problem? Please describe

E2E test covering #3572 and #3565 bugs. Objects or resources deletion redirects to a right place and that navigation links are working (back, close, etc.). 

### Describe the solution you'd like

We should provide a way to verify that UI is not broken after usually deleting some of the objects (image, container, pod, podman machine, kind resource) in the details page (image details, resource details) and that the redirection works back to a proper page. Also we could add some quick test for navigation and links (maybe to individual issue).

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/issues/3572 is already covered by a component test (added in the PR to fix the issue)

**Comment by benoitf** [comment]
and for images, containers, pods it's already tested by component tests

**Comment by deboer-tim** [comment]
+volumes for the complete set. Back-links were also covered by component test but it was testing for the wrong thing and has been fixed. IMHO no need for additional test here.

**Comment by odockal** [comment]
Haven't been through these components tests. But for example resources deletion is also covered?

**Comment by deboer-tim** [comment]
Kind was a good call - #3572 fixed it for all container providers, but the same problem still exists for Kubernetes providers. I opened issue #3594, the same fix and component test can easily be applied.

I can't think of any other resources that are missing, since (e.g.) deleting the Kind container from Container Details is just the same as a regular container.
