### ISSUE TITLE
MSIX installer support

### ISSUE THREAD

**Issue by hansmbakker** [containers/podman-desktop#361]
### Is your enhancement related to a problem? Please describe

MSI installers are quite slow and sometimes do not clean up on uninstall.

### Describe the solution you'd like

MSIX packages have better integration with the Windows OS and have advantages for updates and removal. Overall their install experience feels smoother.

See https://docs.microsoft.com/en-us/windows/msix/overview

**Comment by benoitf** [comment]
Hello @hansmbakker are you speaking about the podman installer ?
If so we should probably move this issue to podman issue tracker

**Comment by hansmbakker** [comment]
This would be nice improvements for both projects I would say - I made a separate request for podman at https://github.com/containers/podman/issues/15129

**Comment by hansmbakker** [comment]
This could be relevant for https://github.com/containers/podman-desktop/issues/302

**Comment by gbraad** [comment]
@hansmbakker the 'Installer' task is mostly the process of the extension to configure podman using the containers/podman provided MSI.

I understand that this issue is to provide an MSI(X) for the actual install process of the podman desktop instead of the current nullsoft (nsis), right? Which benefits are you after? (the steps to add a start-menu item and autostart is something Electron can do, but might not be the best approach). 

In my opinion a combined MSI, that would bootstrap the podman-remote client on Windows and podman-desktop would already provide a better experience as it would be able to handle pre-requisites. However, this might be an optimization we can do later down the line.

**Comment by benoitf** [comment]
closing as won't fix, no votes on the issue and people are using the current Windows installer
