### ISSUE TITLE
Design: Guided flows for dashboard

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#3722]
Simple design for presentation of link on the dashboard to point to "get started with..." tutorials / workflow documentation.

**Comment by mairin** [comment]
Rough idea

![Screenshot from 2023-08-30 14-32-20](https://github.com/containers/podman-desktop/assets/799683/8493035f-6447-479d-b6d0-7c55751fd1ec)

**Comment by mairin** [comment]
This is an alternative design idea, as a carousel - might scale better?

![Screenshot from 2023-11-28 19-10-33](https://github.com/containers/podman-desktop/assets/799683/19306801-3df7-4620-8a8d-48c5828b7a01)

**Comment by benoitf** [comment]
I like the carousel design 👍

**Comment by deboer-tim** [comment]
+1. Should make it a component (e.g. could use for featured extensions as well) and could scale 2/3/4 wide based on the context.

**Comment by dgolovin** [comment]
Created to #5072 for the carousel component.

**Comment by dgolovin** [comment]
Do we want to show multiple `Get started` buttons? It is IMO pretty clear you would have to click on the guide card to open it.

**Comment by dgolovin** [comment]
@mairin I have implementation for "Learning Center' in #5142, there is also video that shows how it works. Screenshot below also includes featured extensions, but it is not part of #5142, because I just used featured extensions to test Carousel component implementation.

![image](https://github.com/containers/podman-desktop/assets/620330/52dd4579-4064-498a-b1d1-5ae8b65b5582)
