### ISSUE TITLE
Investigate telemetry errors

### ISSUE THREAD

**Issue by nichjones1** [containers/podman-desktop#3788]

**Comment by deboer-tim** [comment]
I tried to create some tables/charts from the telemetry errors this afternoon and am coming to the conclusion that we're not outputting errors in a way that makes it particularly easy to do this, nor categorizing or digging into failures. See below for sample errors received today for Compose and Kind for some of the details, but I see two main problems:

1. For extensions most errors are traced as a single event (but separately from the actions that triggered them), which means it's not easy to:
a) gauge the percentage of users hitting a particular problem (e.g. failure vs success rate for creating a Kind cluster) or when a value is 'high' (e.g. is 10 a lot of errors for something? not if there were 10000 attempts). 
b) compare what the difference is between a successful vs failed attempt (e.g. we might notice that there's a higher failure rate on Windows or after upgrading to a particular version).

2. The errors tend to either have very generic properties (e.g. "name: HttpError") that apply to almost every instance, or very specific ones (e.g. path/url) that are usually different. This makes it hard to group or categorize to see if there is a single problem that's causing most of the errors, or a variety of different problems.

(Yes, I know this one is unfair b/c many of the errors are from an executable failing and we really don't have much info - just saying it's a challenge.)

Here are two random examples:

**Compose**

```
"properties": {
    "app_name": "Podman Desktop",
    "app_version": "1.4.0",
    "common.extensionName": "podman-desktop.compose",
    "common.extensionVersion": "0.0.1",
    "error": {
      "name": "HttpError",
      "request": {
        "headers": {
          "accept": "application/vnd.github.v3+json",
          "user-agent": "octokit-rest.js/20.0.1 octokit-core.js/5.0.0 Node.js/18.16.1 (win32; x64)"
        },
        "method": "GET",
        "request": {},
        "url": "https://api.github.com/repos/docker/compose/releases?per_page=5"
      },
      "status": 500
    },
    "sourceError": "install"
  },
```

If you group by sourceError you can see we're only tracing install errors. All events in the last 60 days are very similar:
- error.name (455 HttpError vs 10 blank)
- error.path (7 specific paths vs 458 blank)
- error.url (most common URL failure is the one above, a few for other random pages)

**Kind**

```
"properties": {
    "app_name": "Podman Desktop",
    "app_version": "1.4.0",
    "common.extensionName": "podman-desktop.kind",
    "common.extensionVersion": "0.0.1",
    "error": "Command execution failed with exit code 1",
    "httpHostPort": "9090",
    "httpsHostPort": "9443",
    "ingressController": true,
    "provider": "podman",
    "sourceError": "createCluster",
    "stdErr": "Command execution failed with exit code 1"
  },
```

Again, we're only logging one sourceError so far. There isn't much to group by - grouping by error, 'none' is the most common, then 'No active cluster!', then literally 100 different variations of 'ERROR: failed to create cluster: failed to get podman info (podman info --format json): "": command "podman info --format json" failed with error: exit status 125..'

**Recommendations**

1. For errors involving HTTP requests or executables we should always log `httpStatus` or `exitCode`.

2. Instead of action event + separate error event, we should discuss only having the (post-)action event which has a boolean `success` (or `httpStatus` or `exitCode`), with error properties that only exist when it fails.

3. Especially for HTTP requests/executables, we're going to need to spend some time on each trying to figure out what responses are likely, what we'd want to differentiate, and if there's anything else we can do to make these events unique. (or if it's even worth doing) e.g. for the kind event above we'd be able to group much easier if we cropped the error at 40 chars or included the exit status. Ideally we'd have enough info to distinguish between legitimate user error, usability problem we could improve, defect in PD, or defect in what we're calling.

**Comment by jeffmaury** [comment]
The pattern that I used when I extended telemetry for the Kubernetes client is to extend the event reported to telemetry with an additional error object so that normal and error cases should be similar:

See https://github.com/containers/podman-desktop/blob/4438e3abf6bfc2d8dae5ed9a05b2a2ba5c6f9bc9/packages/main/src/plugin/kubernetes-client.ts#L340

I agree that we should have a document describing the content of the telemetry event and a corresponding coding style
