### ISSUE TITLE
Empty screen when clicking on pod on ocp sandbox

### ISSUE THREAD

**Issue by lstocchi** [containers/podman-desktop#3868]
### Bug description

![empty_screen_pod](https://github.com/containers/podman-desktop/assets/49404737/54c5a894-28a0-4edf-968d-7e6a0b0f7ef0)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.3.1

### Steps to reproduce

1. create a pod on your ocp sandbox cluster
2. click on the pod from the pods list

**Comment by deboer-tim** [comment]
Is there anything in the log/trace? FWIW this is working fine for me on Mac on both 1.3.1 and dev.

**Comment by lstocchi** [comment]
No error in the logs. I'll try to debug it later

**Comment by smfeest** [comment]
I'm seeing something very similar whenever I click Run Image on the Images screen.

Windows 11 / Podman Desktop 1.4.0 / Podman 4.6.2

The logs contain:

```
error : main ↪️ Kubeconfig path C:\Users\feests\.kube\config provided does not exist. Skipping.
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.docker) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kind) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.kube-context) with max activation time of 10 seconds
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima) with max activation time of 10 seconds
debug : main ↪️ [lima] Could not find socket at C:\Users\feests\.lima\podman\sock\podman.sock
log : main ↪️ Activating extension (podman-desktop.podman) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.registries) with max activation time of 10 seconds
log : main ↪️ Activating extension (podman-desktop.compose) ended in 89 milliseconds
log : main ↪️ Activating extension (podman-desktop.docker) ended in 88 milliseconds
log : main ↪️ Activating extension (podman-desktop.kube-context) ended in 59 milliseconds
log : main ↪️ Activating extension (podman-desktop.lima) ended in 58 milliseconds
log : main ↪️ Activating extension (podman-desktop.registries) ended in 45 milliseconds
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 339.6923000216484ms
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 190.98960000276566ms
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
error : main ↪️ [kind] [object Object]
log : main ↪️ Activating extension (podman-desktop.kind) ended in 731 milliseconds
log : main ↪️ Activating extension (podman-desktop.podman) ended in 990 milliseconds
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting container engine
log : main ↪️ [podman] Podman extension: Autostarting machine podman-machine-default
log : main ↪️ Fetched https://registry.podman-desktop.io/api/extensions.json in 85.88849997520447ms
```

**Comment by feloy** [comment]
I can also reproduce the problem on Linux

**Comment by feloy** [comment]
The URL to access the pod details page is `/pods/$kind/$name/$engineId/logs` with `engineId` being encoded with `encodeURI`. 

In the case of ocp sandbox, engineId is in the form `userid-dev/api-sandbox-...-openshiftapps-com:6443/userId`, and `encodeURI` of this value is the same value, '/' not being encoded, and as a result the engineId read by the Details page is incomplete (`userid-dev` only).

To get the value encoded as we want, I think we need to use `encodeURIComponent` instead.

To fix this, we will need to change in all the places where this route is computed to replace `encodeURI` with `encodeURIComponent`, and decode it in `App.svelte` with `decodeURIComponent`.

I would suggest to make a refactor, to define helper functions creating the route with encoded fragment, instead of having the same formula duplicated in every places where the route is defined, so it will be easier to update routes later.
