### ISSUE TITLE
Container created with an error can be supossedly started and is shown running in Containers page

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#3907]
### Bug description

there are multiple wrong information when starting container (that cannot be stared due to upstream bug) from Containers Page. See the attachment.

![rootless-container-error-containers-page](https://github.com/containers/podman-desktop/assets/19164299/e1fd262c-c0cd-4e5c-ac4a-2ef7b8d6ca54)

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

### Steps to reproduce

Follow up of #3899.
1. rootless podman machine
2. pull image alpine
3. start container (expected state is Created because of error)
4. Start container on Containers page -
5. check its status should get back to Created, shows an error, and shows right AGE.

**Comment by alexojegu** [comment]
Same here on Arch Linux with rootless podman and Podman Desktop installed from Flatpak.

Can be related with the update of `conmon` or `containers-common` or maybe `slirp4netns`?
> upgraded conmon (1:2.1.7-1 -> 1:2.1.8-1)
> upgraded containers-common (1:0.55.2-1 -> 1:0.55.3-1)
> upgraded slirp4netns (1.2.0-1 -> 1.2.1-1)

**Comment by alexojegu** [comment]
For me it was fixed after the last update of my system:

> podman (4.6.2-1 -> 4.7.1-1)
> containers-common (1:0.55.4-1 -> 1:0.56.0-1)
> netavark (1.7.0-1 -> 1.8.0-1)
> catatonit (0.1.7-2 -> 0.2.0-1)

**Comment by lstocchi** [comment]
I'm still able to replicate it but i wonder about the correct behavior.
It also happen if you try to create 2 containers that use the same port. The first one succeeds, the second is created but not started.

So the question is, if we create the container but it does not get started, what should we do? We redirect the user to the containers page anyway? We do not redirect and we show an error "the container has been created but not started"? Anything else? @benoitf

**Comment by benoitf** [comment]
@lstocchi I would say there are two issues if we take one approach or the second one

In case on some error, let say the port number is incorrect, I would like to be kept in the creation form because I can quickly change the port number

If I go directly to the details of a container because it's created but not started then it's nice as I can go the logs page and see error, delete the container but I can't recreate it with different value (like the port number)

for the specific use case of the port number, maybe we shouldn't let people click on 'create' as we know it won't be available
like 'fail fast' pattern

I don't know what others think
