### ISSUE TITLE
Can not close Podman Desktop UI

### ISSUE THREAD

**Issue by pacostas** [containers/podman-desktop#396]
### Bug description

Cannot close the window of Podman Desktop despite I press alt+f4 or the X button from the window manager. Also there is no X button on the window of Podman Desktop.

### Operating system

Fedora Linux 36 (Workstation Edition) / Intel® Core™ i7-6700HQ × 8

### Version

0.0.5

### Steps to reproduce

Install podman -> initialize/start podman machine -> Install podman desktop with flatpak or by executing the binary file -> launch podman desktop -> Try to close it.

**Comment by benoitf** [comment]
This bug has been fixed in current milestone (will be in 0.0.6) but is not in 0.0.5

you can try with current pre-releases https://github.com/containers/podman-desktop/releases

like https://github.com/containers/podman-desktop/releases/download/v0.0.202208091459-d977675/podman-desktop-0.0.202208091459-d977675.flatpak for flatpak or https://github.com/containers/podman-desktop/releases/download/v0.0.202208091459-d977675/podman-desktop-0.0.202208091459-d977675.tar.gz for the binary

duplicating https://github.com/containers/podman-desktop/issues/323
