### ISSUE TITLE
Onboarding bug with dynamically updating configuration values.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#3977]
### Bug description

When implementing https://github.com/containers/podman-desktop/pull/3953 I found something odd happening when updating the configuration values.

When I add the onboarding configuration:

```json
    "configuration": {
      "title": "Compose",
      "properties": {
        "compose.binary.installComposeSystemWide": {
          "type": "boolean",
          "default": false,
          "scope": "Onboarding",
          "description": "Install system-wide instead of just your user directory, so compose can be accessed on the command line. Note: You will be prompted for system privileges when enabling this."
        }
      }
    }
```

The boolean default value `false` will *always* show as false in onboarding even if the configuration value has been dynamically updated to true (even before loading onboarding).

For example, if I were to update the value within the code within the `activate` portion of the extension:

```ts
    await extensionApi.configuration
      .getConfiguration('compose')
      .update('binary.installComposeSystemWide', true);
```

It will still not show in the onboarding process as updated, it will always show the `default:` value instead.

Below is a video on what happens:

https://github.com/containers/podman-desktop/assets/6422176/4d8d4860-2c38-449a-b79d-78e4c5e39836

### Operating system

mac M1

### Installation Method

None

### Version

1.4.0

### Steps to reproduce

Run the code from https://github.com/containers/podman-desktop/pull/3953

And see how the value is always false when going to the onboarding page despite the value being updated within `compose/extension.ts`

**Comment by lstocchi** [comment]
@benoitf the problem here is that only the DEFAULT scope is taken in consideration when a property is saved. So if you have a configuration with only the onboarding scope nothing is actually done.
I could extend it to make it work with the onboarding scope as well but .. how? Do i save the onboarding settings in a separate file? Do i save them as an object in current settings.json so that the onboarding section is saved in the onboarding configuration map? Other ideas?

**Comment by benoitf** [comment]
only DEFAULT scope will be stored.
Probably flag an error when starting the extension if you set a property with only 'Onboarding' scope.
Onboarding needs to be an additional scope to the default, else it's not persisted/visible globally


so, DEFAULT scope is OK but OnBoarding scope requires DEFAULT to be present

>  Do i save the onboarding settings in a separate file? Do i save them as an object in current settings.json so that the onboarding section is saved in the onboarding configuration map? Other ideas?

I don't think so, onboarding is only a flag to restrict the set of properties, persistence should occur on the DEFAULT scope

**Comment by lstocchi** [comment]
@benoitf so how can someone hides the setting from the preferences page but still show it in the onboarding? Because this is what Charlie is trying to do. Should the hidden property only affects the preferences page? Should we have another property?

**Comment by benoitf** [comment]
hi @lstocchi we could assume as you suggest that yes hidden is for default scope, not for onboarding

because it's mostly to hide it from the preferences page.

but if you add 'Onboarding' it means it's something you want for the onboarding so it can't be hidden, and if you want to hide it from the onboarding then don't add 'Onboarding' scope.
