### ISSUE TITLE
Cannot install on Windows because Podman Desktop states Hyper-V not installed

### ISSUE THREAD

**Issue by m8-t** [containers/podman-desktop#402]
### Bug description

I want to try Podman Desktop on Windows 10.
When I click "Install" the pre-flight check states that Hyper-V is not installed.
As I already use WSL2 on Windows 10 Hyper-V is mandatory.
I double checked if it is enabled. 
Maybe I am missing a feature here? I do not have administrative rights on the machine but I am able to install VMs on Hyper-V, so I guess this should be okay?

### Operating system

Windows 10 20H2

### Version

next (development version)

### Steps to reproduce

I run Podman Desktop version 0.0.6 (cannot chose from the menu above).

Download Podman Desktop, click on Install.

**Comment by benoitf** [comment]
Hello @dan-m8t thanks to report the issue

The hyper-v check is done there https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/podman-install.ts#L387

Could you run the command in a powershell 
```(Get-Service vmcompute).DisplayName```

And post the output ?

We compare it to be `Hyper-V Host Compute Service`

**Comment by artificial-intelligence** [comment]
fwiw the output from ` (Get-Service vmcompute).DisplayName` is localized to the currently used language, so that check will fail on any non english windows 10 version.

this might help  to force the ouput to be always in your preferred language (i.e. english):

https://stackoverflow.com/questions/19869627/forcing-powershell-errors-output-in-english-on-localized-systems/19870547#19870547

**Comment by benoitf** [comment]
Thanks for the answer

For now, as workaround you can execute the MSI installer from there
https://github.com/containers/podman/releases/download/v4.2.0/podman-v4.2.0.msi
