### ISSUE TITLE
Lima: Document how to select which provider and which instance to use.

### ISSUE THREAD

**Issue by themr0c** [containers/podman-desktop#4069]
We might want to document how to select which provider and which instance to use.

It will default to "podman", but if you use "docker" or "kubernetes" (instance "k3s" or "k8s") you have to change it.

It is currently located under "Preferences: Lima", it is a simple drop-down - but might be tricky for the user to find:

![pd-lima-extension-podman](https://github.com/containers/podman-desktop/assets/10364051/9b5e4494-81a4-4aba-81ff-04a411440b12)
![pd-lima-extension-docker](https://github.com/containers/podman-desktop/assets/10364051/f003d07d-51ec-4666-81e8-23c14906dea6)
![pd-lima-extension-k8s](https://github.com/containers/podman-desktop/assets/10364051/a176dd4a-227f-4883-ba1e-65c26db05efd)

For the kubernetes addition, one also has to modify the kubeconfig search path - until that can be automated.

----

All of it is somewhat temporary, the best for the default path would be to create the machines like with podman.

* https://github.com/containers/podman-desktop/issues/3069

Then the user would decided if they want to run "containers" or run "kubernetes", with all the other VM options:

* https://github.com/containers/podman-desktop/pull/2902

_Originally posted by @afbjorklund in https://github.com/containers/podman-desktop/issues/3990#issuecomment-1733198450_

**Comment by afbjorklund** [comment]
Currently the supported container engines/runtimes look something like this:

* containers (1)
  * podman
  * docker
* kubernetes (2)
  * containerd (k3s)
  * containerd (k8s)

1)
containers:
There is no support in Podman Desktop, for using `nerdctl` containers directly.
Otherwise that would be a possibility too, to use only ctr/buildctl without kubectl.

2)
kubernetes:
There is currently no interest in running with docker* or with "podman" (i.e. cri-o)
So all the current solutions (including kind) are using containerd for their clusters.

\* with cri-dockerd
