### ISSUE TITLE
"Hidden" value for Providers (do not show in dashboard)

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4196]
### Is your enhancement related to a problem? Please describe

When implementing https://github.com/containers/podman-desktop/pull/3953

We have to add 'installed' and 'not-installed' for the provider.

The only problem is that this makes it appear in the front dashboard.

Since Compose is only really installing a binary and making sure it's also installed system-wide, it doesn't seem necessary to have it show all the time / show the status / etc.

### Describe the solution you'd like

Add a `hidden` value for an extension so that it does not show on the dashboard / frontpage of podman desktop.

**Comment by lstocchi** [comment]
Thinking aloud ... maybe we should just think which is worth to be shown on the dashboard and filter by that.
E.g if the provider does not have any `*connectionFactory`, it will not be used to create any container so it's not worth to be displayed in the dashboard.

Having the `hidden` prop may work but then i think that nobody will use it because it's kinda losing visibility...  you are an external developer that creates an extension, you do not add the hidden prop bc you always wants to show it in the dashboard. Why should i want to add it?

Another thought is .... maybe after the dashboard refactoring it will not be needed?? 🤔

**Comment by benoitf** [comment]
I think also that we should avoid `hidden` property

Dashboard entries will be revisited, etc so better to display setup button with unknown state, @lstocchi suggestion (but for example Docker extension won't be displayed in that case?), etc

**Comment by deboer-tim** [comment]
+1 to both prior comments. It's opening up a can of worms, but I think we need to look at what we think the dashboard will/should look like a few months from now (will all providers appear there? what will they look like?) and plan around that.

**Comment by cdrage** [comment]
Dashboard has been refactored and this is not relevant anymore / resolved.
