### ISSUE TITLE
Show onboarding based on "enablement" property rather than based on status

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4207]
### Is your enhancement related to a problem? Please describe

As a result of discussions in https://github.com/containers/podman-desktop/pull/3953 the "onboarding" / "Setup..." process should show as a result of checking the "enablement" property of onboarding, rather than the current implementation of checking the provider status.

The reasoning is that there are some extensions such as Compose (and in the future possibly Kind..) where we do not want it to appear in the dashboard, but still have a way to indicate that a "Setup..." is required as part of onboarding.

### Describe the solution you'd like

Setup button showing as a result of enablement property within `package.json` rather than provider status.

**Comment by lstocchi** [comment]
Just to clarify, we already check the enablement clause, together with the provider status.
https://github.com/containers/podman-desktop/blob/ef66a2e5bd38f71e3c67e9fdc1053f7c051a84f5/packages/renderer/src/lib/preferences/PreferencesResourcesRendering.svelte#L372

The fact is that if the enablement is true and the provider status is `not-installed`, we show the `Setup` button.
If one of the two is not true, we show the gear button which opens the onboarding if it has not been completed yet or the extensions settings otherwise.
