### ISSUE TITLE
Inconsistent Kind status

### ISSUE THREAD

**Issue by dougbreaux** [containers/podman-desktop#4267]
### Bug description

The graphic buttons show Kind installed, but the status bar shows a warning that it is not installed. In my case, I don't want/need it, so it's not affecting my usage. But it's confusing at best.

![image](https://github.com/containers/podman-desktop/assets/25640850/9223e62d-c082-4f58-9774-8c87cb3943e1)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

**Comment by lstocchi** [comment]
The `kind installed` square that you see in the dashboard is related to the kind extension (which contains the logic to download the kind cli, create a kind cluster, ...).

The kind in the status bar is related to the binary. 

The `kind extension` is not able to detect any `kind binary` in your system and it warns you that you need to install it.

If you do not plan to create/use a kind cluster you may think to disable the extension. This should remove the kind warning in the statusbar.

**Comment by dougbreaux** [comment]
@lstocchi Ok, thanks. Then I suppose the ask would be to make that more clear in the UI 🙂

**Comment by lstocchi** [comment]
@mairin we need your help here :)

**Comment by mairin** [comment]
@lstocchi The separation of the extension vs. the thing *is* super confusing. I think if I could hit rewind from the beginning, I might rename the extensions... like instead of saying "Kind  //  Installed" I'd have it say "Kind Support // Enabled"

I would also not have the extensions quite so prominent in the dashboard anymore, because, out of the box most of them are installed by default anyway. Maybe it should only show up on the dashboard as featured if it is not installed?25

**Comment by deboer-tim** [comment]
> Maybe it should only show up on the dashboard as featured if it is not installed?

I think you originally included them in the mockup for the welcome page because we wanted to show all the things you had support for already installed plus what else is available, but for everywhere else I agree (or maybe there's even a different way to show that up front?). The risk is that I have support for something but forget or don't know where to start, but I think future dashboard notifications is a better place to give users a hint.

I also feel like we could do a couple minor things to differentiate between extension = support for something vs the actual install of something, but no concrete ideas atm. e.g. Maybe use a consistent icon or text treatment for extensions.

**Comment by jeffmaury** [comment]
Maybe use sêparate working: installed (extensions) vs available (providers)
