### ISSUE TITLE
[Style guide] Flexbox mockup of Settings > Registries screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4294]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of the Settings > Registries screen. Non-flex mockup components for the registries screen are in the "Modal form-1" page of [the Main Design File](https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/c1a43240-198d-11ed-817f-f940e3befd53?page-id=121e1e70-40b7-11ed-a607-0f43818c2e21).

Here is a screenshot of the screen:
![Screenshot from 2023-10-11 15-19-26](https://github.com/containers/podman-desktop/assets/799683/ae18ae9e-73b8-440f-adc1-ebb3fa70ff5d)

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/78e08688-f409-422b-a84b-4cdb1900d978)

These can be found in the penpot file here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0

Board name is: https://github.com/containers/podman-desktop/issues/4294 Settings > Registries

**Comment by benoitf** [comment]
hello, it seems the current implementation differs from the mockup, there is a kebab menu with some actions, etc

here I just see Configure on all the lines but I think it's missing the state where something has been added

**Comment by deboer-tim** [comment]
Also, what happens when you click on Add? Currently it creates a temporary row at the bottom of the table, but maybe should be a form/dialog to be consistent with e.g. creating a volume?

**Comment by ekidneyrh** [comment]
Looked at this in the UX meeting - reopening to add different states and play around with the inline fields.

**Comment by ekidneyrh** [comment]
Okay, so I redid this. I moved the login action to a separate pop-up dialog. By doing this, we can get rid of the username and password columns from the table. We can also make those rows smaller and have two registries per row. 

Added icons to the rows instead of the purple primary button to match the table layout. I have the config as a cog, and then I was not sure if we are able to delete registries from here, but if so there's the option of adding the trash can. 

Registry screen:

![registry-screen-draft](https://github.com/containers/podman-desktop/assets/87311656/8c75ae74-cb91-4843-93a6-5e55b5a7259b)

Pop-up:
![Screenshot from 2024-07-02 13-07-44](https://github.com/containers/podman-desktop/assets/87311656/737009bd-43e8-47a6-a434-14266c23fb2a)

**Comment by deboer-tim** [comment]
The built-in registries like Quay have names/urls/icons that you can't change (and if you add a registry yourself you can't name or give it an icon). It's not clear what the Edit dialog for these would look like - maybe icon/name are in the title and url input is disabled?

Also, Login can fail. Currently the error is added in-place and the user can't make the change. Maybe we should leave space under user/password for an error so the dialog doesn't expand in this case?

On the implementation side we may need to break this up, e.g. creating the add/edit dialog and then switching to tiles. Once we've clarified the comments above I think we can open an issue for implementation/prioritization and close this.

**Comment by ekidneyrh** [comment]
> The built-in registries like Quay have names/urls/icons that you can't change (and if you add a registry yourself you can't name or give it an icon). It's not clear what the Edit dialog for these would look like - maybe icon/name are in the title and url input is disabled?

Yeah, having those fields disabled would work. If you could, would you mind sending screenshots of what currently is the screen when configure is pressed, and you're logged in? I'd be able to work off that then and suggest changes.

But as far as the ADD dialog goes, would the above mockup work for that? And then I can make another mockup dialog for the EDIT. 

> Also, Login can fail. Currently the error is added in-place and the user can't make the change. Maybe we should leave space under user/password for an error so the dialog doesn't expand in this case?

Yes having a space underneath dedicated for the error message would work. That's the best way to do it, I think. 

> On the implementation side we may need to break this up, e.g. creating the add/edit dialog and then switching to tiles. Once we've clarified the comments above I think we can open an issue for implementation/prioritization and close this.

So it would be an issue for:
1. Add dialog
2. Edit dialog
3. Changing table to tiles

**Comment by ekidneyrh** [comment]
_Discussed this on the UX call last Thursday 2024-07-04._ 

When you log in, it goes back to the previous state with the addition of displaying your username in the column. If there’s an error, the row will expand to fit the error message under the input field.  

Avoid displaying the different locations as cards to keep consistent with the rest of the application. Also keep the username column to indicate that the user is logged in. 

We could add in a status to allow the user to know they are still connected to the registry.

**Comment by ekidneyrh** [comment]
Here's updated mock-ups based on the feedback:

![Screenshot from 2024-07-10 12-55-40](https://github.com/containers/podman-desktop/assets/87311656/1d17ec20-1e8d-4a23-bb11-6eca68f75084)

Back to rows, so it is consistent with how we display items on tables. Have just the username displayed when logged in, having the password dots seems redundant. Adding in a connect status label, the same as those used on the dashboard at the moment, just changed to say 'CONNECTED' or 'DISCONNECTED'. Only have them appear when there are credentials saved. 

The pop-up to add a registry have a red error message if the credentials are incorrect. I'd recommend having a space underneath dedicated for the error message, whether it's displayed or not so that the dialog box doesn't change in size when the error is present.

![Screenshot from 2024-07-10 12-53-03](https://github.com/containers/podman-desktop/assets/87311656/bbd84703-4665-4f90-bc88-7cc673b0d374)

**Comment by odockal** [comment]
This will require to redo the e2e tests.

**Comment by deboer-tim** [comment]
+1 to overall design, cleaner and simpler. A few comments:
- Not 100% sure if connected/disconnected is right since we only validate once, maybe just 'verified' or something.
- Should we just use the table component here? Checkbox column is already optional. Not clear if there should be a header row here but that could easily be optional too.
- The error can go inline with the Cancel/Login buttons to avoid a newline (we did that for the Feedback dialog so any dialog can use it now).
- It would be good to see what editing one of the preconfigured registries like Quay looks like, since they have a name/icon/url that is fixed.

**Comment by ekidneyrh** [comment]
> +1 to overall design, cleaner and simpler. A few comments:
> 
>     * Not 100% sure if connected/disconnected is right since we only validate once, maybe just 'verified' or something.

On the UX call it was discussed validating more often to see if the credentials were still working and tell the user when they need to be updates, e.g. through the 'disconnected' label. Is this something that can be implemented at some stage and maybe have the verified as a placeholder till then?

>     * Should we just use the table component here? Checkbox column is already optional. Not clear if there should be a header row here but that could easily be optional too.

We could! For the headers something similar to whats already there like: registry location, username, status, actions.

>     * The error can go inline with the Cancel/Login buttons to avoid a newline (we did that for the Feedback dialog so any dialog can use it now).

I originally though f just having the box the same height regardless of the error message or not but f that makes it easier to implement then +1

>     * It would be good to see what editing one of the preconfigured registries like Quay looks like, since they have a name/icon/url that is fixed.

The cog is in place for the configure button, so I would assume it's just to update credentials if necessary.

**Comment by deboer-tim** [comment]
👍🏼 on the other responses.

> > ```
> > * It would be good to see what editing one of the preconfigured registries like Quay looks like, since they have a name/icon/url that is fixed.
> > ```
> 
> The cog is in place for the configure button, so I would assume it's just to update credentials if necessary.

Yes, I just meant the header of the dialog would look different in this case, e.g. maybe the title would be 'Edit Red Hat Quay', and the URL field would be readonly?

**Comment by ekidneyrh** [comment]
> Yes, I just meant the header of the dialog would look different in this case, e.g. maybe the title would be 'Edit Red Hat Quay', and the URL field would be readonly?

Apologies, I interpreted your reply wrong! 

Yes to both of those suggestions :) 

![dialog](https://github.com/user-attachments/assets/cd90ef5c-86d9-421b-99c1-b5c92145bea7)

**Comment by ekidneyrh** [comment]
Opened https://github.com/containers/podman-desktop/issues/8103 to implement new mock-ups :) Closing as complete
