### ISSUE TITLE
[Style guide] Flexbox mockup of form screen

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4296]
This is part of epic #4289 ([Design] Style Guide)

We need a penpot flexbox mockup of a form screen. Should be based on the design of the deploy to kubernetes screen eg
![Screenshot from 2023-10-11 15-27-23](https://github.com/containers/podman-desktop/assets/799683/d134bdd7-da80-40fe-b646-aa41d54b0645)

**Comment by deboer-tim** [comment]
The design should include what happens when you click the 'go' button at the bottom. We currently have 3-4 different behaviours, from showing terminal windows to progress bars, or just creating a task. I assume we still need at least two different options (e.g. forms where you would normally wait for the result vs background tasks).

For background tasks, I'm assuming all future status/notification is handled via the task manager. But where does the task link go to?

For non-background tasks we need to know where progress is shown (header? bottom of the form below the button?) and how success vs errors are handled (e.g. issue #4229 where the current error message may be hidden by default - do we auto scroll?).

**Comment by ekidneyrh** [comment]
![image](https://github.com/containers/podman-desktop/assets/87311656/7ec5db3c-b9a1-4d2b-a953-100a4d8ae8c8)

![image](https://github.com/containers/podman-desktop/assets/87311656/fbf4601a-d37a-46cb-88af-80ed3dd03ca6)

![image](https://github.com/containers/podman-desktop/assets/87311656/640b8425-5ba5-43e4-b476-0107a997db33)

These can be found in the penpot file here: https://design.penpot.app/#/workspace/82e31d90-3829-8139-8002-cb67c32e72ca/8ec95363-4e2c-80a4-8002-cb67c874d0be?page-id=845b2be9-256a-8073-8002-cb7680a37cf0

Board names are: #4296 Form Screen 1 - 3
