### ISSUE TITLE
Onboarding UI: Add "max-width" for onboarding steps

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4321]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-10-12 at 2 48 25 PM](https://github.com/containers/podman-desktop/assets/6422176/0fa71892-6603-4fa0-963d-2ecffc46e997)

Reference: https://github.com/containers/podman-desktop/pull/4179#pullrequestreview-1674304330

There should be a "max width" for the portview for the steps as the buttons / paragraphs go to the edge of the page.

### Describe the solution you'd like

Smaller width to improve visuals.

**Comment by lstocchi** [comment]
@mairin which should be the max-width for the onboarding? On the resources page we have `905px` for each provider card.

On a wide screen it gets ugly otherwise, i could also potentially have all the text in one row
![image](https://github.com/containers/podman-desktop/assets/49404737/f3f41684-baa1-4b94-8e3c-edc2b4dcaf7b)

**Comment by mairin** [comment]
@cdrage I'd use `905 px` as well if resources is! Does it look off?
