### ISSUE TITLE
Old podman version warning

### ISSUE THREAD

**Issue by mairin** [containers/podman-desktop#4345]
### Is your enhancement related to a problem? Please describe

I read this review of Podman Desktop:
https://www.zippyops.com/podman-desktop-review#

I think the author has a good idea:

![Screenshot_20231014_182456_Firefox](https://github.com/containers/podman-desktop/assets/799683/005ba9db-e416-4931-b3ec-137656a7b332)

### Describe the solution you'd like

Maybe on the first onboarding screen, add a little block that says something like, 

"We auto-detected Podman version 3.4 on your system. This is an old version and you may face some unexpected errors. Please consider upgrading to Podman $LATEST."

This could also be a dismissable notification on the dashboard.

@themr0c could word this much better I think!

### Describe alternatives you've considered

Another idea... if we can detect Debian-derived distros like Ubuntu on the download page, maybe call out this issue too on the download page?

**Comment by afbjorklund** [comment]
But Podman 3.4 _is_ the latest version provided by the project, so posting a warning about it just rubs it in

What is it really trying to say? Something like "You should have used Fedora instead" perhaps

**Comment by afbjorklund** [comment]
Some alternative suggestions:

1) Force "someone" into making an official PPA
2) Run Podman latest/greatest in a Fedora VM
3) Make it more backwards compatible, backport more
4) Run Docker Engine instead, with your Podman Desktop

**Comment by mairin** [comment]
> But Podman 3.4 _is_ the latest version provided by the project, so posting a warning about it just rubs it in
> 
> What is it really trying to say? Something like "You should have used Fedora instead" perhaps

I really appreciate this perspective!! I absolutely have an undeniable bias towards Fedora (having designed the logo 😆 amongst other things), but! I wouldn't want to push the user to change OS / distro to use Podman Desktop. That's a huge upheaval and takes a lot of effort and consideration (at least until immutable desktops are the norm!)

The point here is more about trying to set expectations. The gap is so wide from today's podman to a 2+ year old release and a full major release version back. I believe that's an unsustainable testing matrix for any team, and as a UX person I'd rather us deliver something 100% excellent and solid for a narrow / recent set of podman releases than something that necessarily will need to be 50% mediocre for all across an amazing breadth of podman releases. 

I think trying to fight a losing battle there is going to be really harmful for the brand of the project; it'll be associated with brokenness. It took us many years (maybe 10?) to get past Fedora's "bleeding edge" perception.

I have seen multiple reviews from Linux users complaining about instability in Podman Desktop and I frankly do not see the same issues as a Linux user. It honestly quite typically comes down to an ancient versiom of Podman. The very least I think we can do is point out the potentially rocky road ahead if we detect a really old version to at least proactively set expectations.

Maybe we can offer a podman machine version for distros with older native podmans? Basically your #2 idea. 

But I would suggest in the meantime we at least give a heads up / qualify the user's experience in this unfortunate context.

**Comment by afbjorklund** [comment]
> But I would suggest in the meantime we at least give a heads up / qualify the user's experience in this unfortunate context.

Probably a good idea. Next year, I think the system version will have "caught up" (it is currently at 4.3.1) . And then you will probably get the "you are not using Podman 5!" warning instead... But maybe this time without the API warning. (?)

```
Error: unable to connect to Podman socket: server API version is too old. Client "4.0.0" server "3.4.2"
```

I still think expecting to be able to run a container was reasonable, even when running an "ancient" version... But unfortunately the reviewer did not say which error was in the log, or maybe he was unable to find the log in the UI ?

> "A black screen is shown, and no container is started."
> At the time of writing, it is not possible to start a container via Podman Desktop.

Requesting uid 262143 bugs out on most rootless containers, since the default allowance is "only" 100000
But it works in rootful, so some people are surprised (maybe they were **not** running Docker as rootless?)

* https://github.com/containers/podman-desktop/issues/3444

It's even worse if you try to run it without any subuid (like in HPC), since then most containers won't work OK...
Again the expectation is different, since it would have worked with `sudo podman` but they changed both at once.

----

Anyway, we changed the Lima instance away from the standard Ubuntu over to Fedora due to the lack of packages...

* https://github.com/lima-vm/lima/commit/6cc3f3f0c6179635d09e264769c6e76fa725e4ba

But we were also able to change the Lima instance for Apptainer back to Ubuntu from Fedora, after they added a PPA.

* https://github.com/lima-vm/lima/commit/cb2f15950749347a4cca15f09e76fdb81a5c3f7d

So if there were packages made available, with a less deprecated and scary warning than Kubic, that would "fix" it.

Or if doing something similar to CRI-O (with Nix) or containerd (with Dockerfile), and provide an all-in-one bundle?

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman.io/pull/240

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/issues/3068

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman-desktop/discussions/5762
