### ISSUE TITLE
Improve selection screen for Containerfile or Existing image

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4383]
### Is your enhancement related to a problem? Please describe

![Screenshot 2023-10-17 at 7 13 14 PM](https://github.com/containers/podman-desktop/assets/6422176/929c269e-9b46-4de6-b053-eb4a643cfc6e)

For this screen, I feel like we could really improve it.

The information is just repeating what the buttons are saying.

As well as the fact that we mention "or Dockerfile" in the button, but nowhere else within Podman Desktop.

We should always mention Containerfile as it's the neautral term to reference a "container building file", but also mention somewhere that it's the same as Dockerfile. 

### Describe the solution you'd like

Cleaner selection screen.

**Comment by cdrage** [comment]
@mairin If you have any suggestions that'd be awesome, to be honest I wasn't sure from a UI perspective what I'd suggest.

**Comment by mairin** [comment]
Hey @cdrage ! I think actually this is a wargames style situation: the best way to win is not to play :-)

I'll look thru Penpot to see if I have mockups but I remember this dialog coming up as a topic of conversation a while ago.... I think the solution here is instead of having one button => pop up wuth two buttons, it would be better to have one button that has a drop down with additional options.

So the button says "Create Container" with a little dropdown arrow.... you click it, and theres a dropdown that says

"From Containerfile / Dockerfile"
"From Image"

And if we wanted to be opinionated we could make the button clickable without engaging the dropdown and default to one of the two (maybe the Containerfile option?)

**Comment by mairin** [comment]
Here's the mockups - the dropdown here is based on the action button dropdown 

![Screenshot from 2023-10-17 20-39-20](https://github.com/containers/podman-desktop/assets/799683/0cf7648b-2e8c-4d2e-94a0-7d16d15b64ff)
![Screenshot from 2023-10-17 20-31-01](https://github.com/containers/podman-desktop/assets/799683/d1ceca3e-b01d-45c4-963b-101acde5d78f)

(Note the container list there isn't perfectly in sync with what we have today, it's an old mockup)

**Comment by cdrage** [comment]
Still valid / would be nice to have instead of having to use a modal.
