### ISSUE TITLE
Compatibility with podman 4.x and above

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#44]
### Is your feature request related to a problem? Please describe

For the time being, the tool is compatible only with Podman 4.x and above.

### Describe the solution you'd like

When starting, the tool should pre-check the version of podman.
If the version detected is older than 4.0, we should display a notification to the end-user and provide instructions on how to upgrade podman.
Ideally, we would also display the latest version number available for podman.

### Describe alternatives you've considered

Eventually, we could also display a "Provider update status" in the system tray.
We could display to the end user that a new version is available and could be installed.

**Comment by afbjorklund** [comment]
The Lima podman instances are **only** available with Podman 3, due to the Podman project dropping support for Ubuntu:

* https://github.com/containers/podman/issues/13302

* https://packages.ubuntu.com/search?keywords=podman&exact=1

In order to use podman4, it needs to use fedora for the underlying distribution - which is available, but only with containerd...

* https://github.com/lima-vm/lima/blob/master/examples/podman.yaml

* https://github.com/lima-vm/lima/blob/master/examples/fedora.yaml

----

EDIT: lima now uses fedora

* https://github.com/lima-vm/lima/commit/6cc3f3f0c6179635d09e264769c6e76fa725e4ba

**Comment by rhatdan** [comment]
"Podman project dropping support for Ubuntu" is a little overboard.  Podman is relying on Ubuntu as well as other distros to ship Podman. The upstream project does is not shipping Ubuntu versions.

**Comment by afbjorklund** [comment]
> The upstream project does is not shipping Ubuntu versions.

Sorry, that is what I meant. No upstream packages, like in Kubic

And Ubuntu does ship Podman (in "universe"), just not version 4

https://packages.ubuntu.com/podman

**Comment by afbjorklund** [comment]
And it would be possible to change the Lima example to use Fedora instead, currently it uses version 3.2.1 which is harder to find clients for...

https://packages.ubuntu.com/impish/podman

**Comment by benoitf** [comment]
podman 4.x and above requirement is for podman binary ( and podman machine on mac/Windows) as only in v4 a socket is mounted on the Host

With Lima it's already working as there is a socket mounted in `$HOME/.lima/podman/sock/podman.sock` on the host.

**Comment by rhatdan** [comment]
Yes no upstream packages for Ubuntu on Kubic.

**Comment by alexanderadam** [comment]
> Yes no upstream packages for Ubuntu on Kubic.

Is there any recommended way of [installing upstream packages on Ubuntu 22.04](https://askubuntu.com/questions/1414446/whats-the-recommended-way-of-installing-podman-4-in-ubuntu-22-04)?

**Comment by slemeur** [comment]
Closing this issue as the requirement for Podman Desktop has been fulfilled
