### ISSUE TITLE
K8s pods actions

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4402]
### Is your enhancement related to a problem? Please describe

Pods running on Kubernetes do not have appropriate menu items for common actions.

### Describe the solution you'd like

Make sure the following actions exist in the pods list for pods running on Kubernetes:

- Open terminal
- Open browser
- Open logs
- Restart
- pause/stop/start if possible

**Comment by deboer-tim** [comment]
FYI @vzhukovs

**Comment by vzhukovs** [comment]
PR for the restart action button: https://github.com/containers/podman-desktop/pull/5174

**Comment by cdrage** [comment]
> ### Is your enhancement related to a problem? Please describe
> Pods running on Kubernetes do not have appropriate menu items for common actions.
> 
> ### Describe the solution you'd like
> Make sure the following actions exist in the pods list for pods running on Kubernetes:
> 
> * Open terminal
> * Open browser
> * Open logs
> * Restart
> * pause/stop/start if possible
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_


There are some Kubernetes concepts where adding Restart or Open Browser doesn't make sense for Pods.

- Open terminal = Makes sense
- Open browser = You would have to check to see if that Pod is connected to a Service, and then an Ingress too and find the appropriate link. I don't believe adding Open Browser for a Pod would be applicable as you'd have to query the service/ingress. What other common tools use is instead of open browser,  is use the "port forward" functionality of Kubernetes and then be able to view the pod locally at a random port number.
- Restart = I don't believe this makes sense as there is no concept of restart in Kubernetes but rather a "delete and then re-create". This concept would be applicable to something like Podman pods, but for Kubernetes, Pods are managed by Deployment / ReplicaSet / DaemonSet / etc and it's the responbility of that controller to schedule / delete / create Pods. I believe that **alternatively we can call it "Recreate" instead?**.


Actions I would totally add in order of importantance):

- Port forwarding (very useful for pods)
- Edit YAML (VERY useful for editing environment variables inside of the Pod as a temporary measure.. for example I can edit the YAML, test it out.. and if I want it to revert I can easily delete it and the Deployment / ReplicaSet / etc would re create it).
- Edit terminal
- Export YAML (be able to download & deploy it elsewhere)
