### ISSUE TITLE
Design for Deployments page

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#4403]
### Is your feature request related to a problem? Please describe

Kubernetes!

### Describe the solution you'd like

We need a design for an initial Kubernetes Deployments page, to be implemented by #4366.

**Comment by ConorC117** [comment]
Link to Deployments List page: 

https://design.penpot.app/#/workspace/76981dd7-ec3b-802f-8001-9a56ef3fbc9d/18f3baa5-c6db-81d1-8002-9f756ec487eb?page-id=88a72dea-ea00-80c5-8003-65badc968c16

**Comment by deboer-tim** [comment]
Current screenshot:
<img width="810" alt="Screenshot 2023-11-07 at 8 38 14 AM" src="https://github.com/containers/podman-desktop/assets/19958075/b2c7e829-4494-4df8-a836-b11e0c708c61">

**Comment by deboer-tim** [comment]
@mairin I just noticed that both this design and Ingress/Routes don't have any nav icon on the left. We don't need a mockup for that, but we do need svgs to use. Any chance you can round one up? (and may as well prep Services too, since that's in the pipe)

**Comment by mairin** [comment]
@ConorC117 can you create an icon for deployments based on the kube icon here with the loopy arrow? (upper right)

https://uploads-ssl.webflow.com/5e5a5c35a623e45f7f701878/5e99435c7ab3fdfb624ac319_Screen-Shot-2020-03-11-at-12.50.59-AM-768x616.png

**Comment by cdrage** [comment]
> Current screenshot: <img alt="Screenshot 2023-11-07 at 8 38 14 AM" width="810" src="https://user-images.githubusercontent.com/19958075/281058244-b2c7e829-4494-4df8-a836-b11e0c708c61.png">

My feedback:

- The "Reasons" column is odd as "Reasons" are shown as an array of events for errors. Instead, if it is has a warning, we should hover over the "Warning" symbol and then use Tooltip.svelte to show what the warning / error is.

![Screenshot 2023-11-09 at 8 21 25 AM](https://github.com/containers/podman-desktop/assets/6422176/72437877-63ae-4334-8009-a0d44d94b486)


- Pods we could possibly work in the dots there? One thing too is that having it as 1/2 Pods may be difficult to figure out which pod is not working correctly.


https://github.com/containers/podman-desktop/assets/6422176/8321dbfa-e3e8-4551-96df-1b6a58869771

See this example from the open source version of Lens. There are two pods, but one of them is working (since it's using the correct image), but I re-deployed the Deployment YAML with an incorrect Pod and the other one has problematic image. We will have to show somehow healthy pods vs non-healthy pods, and I believe using the "Dots" from the PR: https://github.com/containers/podman-desktop/pull/4646 would be beneficial.

- "Conditions" section is good in terms of showing Available and Progressing. From this PR with the environment column: https://github.com/containers/podman-desktop/pull/4583 maybe we should take similar design from how we show environment and instead make "Available" and "Progressing" label like so they stand out / more uniformed like the environment columnn in Pods / Containers.

![Screenshot 2023-11-09 at 8 30 20 AM](https://github.com/containers/podman-desktop/assets/6422176/b6fad400-f26e-438e-98c4-e0b0badc3678)

**Comment by benoitf** [comment]
It looks like in the mockup the icon is the 'refresh icon'

maybe use another kind of icons like https://www.flaticon.com/free-icon/deployment_6822231

**Comment by deboer-tim** [comment]
Updated icon proposal in context:
<img width="60" alt="Screenshot 2023-11-16 at 11 46 26 AM" src="https://github.com/containers/podman-desktop/assets/19958075/ffdf1a56-a7e3-4594-9953-d0d7e4d5d102">

**Comment by ConorC117** [comment]
Screenshot of updated Deployments list: 
Note: The cluster namespace would be set to "default" by default, it's just set to "all" for demonstration purposes.

![image](https://github.com/containers/podman-desktop/assets/99751994/f4bec2f1-22b7-4514-92f0-4acbad116a35)

Any general feedback would be really appreciated.

@cdrage If you wouldn't mind taking a quick look at the visual representation of the conditions and pods and letting me know if they currently make more sense now too, I'd really appreciate that!

**Comment by cdrage** [comment]
> Screenshot of updated Deployments list: Note: The cluster namespace would be set to "default" by default, it's just set to "all" for demonstration purposes.
> 
> ![image](https://user-images.githubusercontent.com/99751994/284397609-f4bec2f1-22b7-4514-92f0-4acbad116a35.png)
> 
> Any general feedback would be really appreciated.
> 
> @cdrage If you wouldn't mind taking a quick look at the visual representation of the conditions and pods and letting me know if they currently make more sense now too, I'd really appreciate that!

Okay that looks AWESOME! ALl good with the changes :) that looks great to me.

**Comment by ConorC117** [comment]
Perfect, thank you :)

**Comment by deboer-tim** [comment]
Initial page delivered, just needs improvement to pods column. Since the design is complete I'm closing this and we'll open up new issues if there is any feedback/future improvements.
