### ISSUE TITLE
Using `docker compose` requires DOCKER_HOST, should we add more functionality?

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#4496]
### Is your enhancement related to a problem? Please describe

![screenshot_from_2023-10-24_10-09-09](https://github.com/containers/podman-desktop/assets/6422176/b5740bfb-12a9-4df4-8f08-ae67c7db63c4)

When doing onboarding we are told to enable compatibility mode.

In reality, we have to enable compatibility mode AND set the DOCKER_HOST for `docker compose` to work correctly against a podman machine.

This breaks the "flow" of onboarding.

We added `podman compose` upstream so we do not have to set DOCKER_HOST all the time. However, if users still want to use `docker compose` against a podman machine VM, we have no choice but to set the environment variable.

### Describe the solution you'd like

Think of better ways to integrate telling the user to say to enable compatibility mode as well as use DOCKER_HOST.

**Comment by jeffmaury** [comment]
Why do we need to set DOCKER_HOST if compatibility mode is on ?

**Comment by benoitf** [comment]
but we want to promote 'podman compose' usage

so probably a shorter message and then have a pointer to the documentation for more usecase like 'docker compose' or 'docker-compose'

let say I don't have docker installed on my computer, I want an alternative so I should use 'podman' commands instead of 'docker' commands by default

using docker tools against podman socket is maybe more an advanced usecase and requires pointer to the documentation ?



Regarding the question, why do we need to set DOCKER_HOST environment variable ? we do not bind the docker socket at the expected location on Windows ? docker-compose on Windows is not searching the location ?

**Comment by jeffmaury** [comment]
I can confirm that `DOCKER_HOST` is not required if compatibility mode is enabled: docker-compose uses the default context which is bound to `docker_engine` socket. I've tested this configuration with one of the projects from awesome-compose
