### ISSUE TITLE
Provide default behaviour for double-click on Podman Desktop system icon

### ISSUE THREAD

**Issue by krachynski** [containers/podman-desktop#4500]
### Is your enhancement related to a problem? Please describe

It would be cool if double-clicking the Podman Desktop icon in the System Tray (Windows) or the Menu Bar (macOS) opened the Dashboard. I'm constantly double clicking, often twice, before reaching for Right Click and select Dashboard.

### Describe the solution you'd like

Double-Click should be the equivalent of click/right-click and pick Dashboard.

**Comment by totkeks** [comment]
Was looking for this, because I have the same problem. It's just muscle memory, because every other program has this as their default behavior, if they have a GUI. Double click opens it.

I could even look how to implement this myself and provide a PR, if someone could point me in the right direction.
