### ISSUE TITLE
minikube extension as featured extension

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#4596]
### Is your enhancement related to a problem? Please describe

Minikube can provide a way to have the most efficient 'load/share images' by using podman and cri-o altogether (no extra step)

while for now kind is provided as default, we could use minikube as well

### Describe the solution you'd like

Include the extension as default

### Additional context

Need to see how to include extensions that are in 3rd-party repositories

**Comment by afbjorklund** [comment]
Currently the minikube support for cri-o is not stellar. The versions are out-of-date, and rootless and v2 have issues.
Since podman is not available for ubuntu, it might even require switching to a custom fedora-based image (for KIC)?

**Comment by benoitf** [comment]
on my side it's working with a ubuntu kicbase image `quay.io/fbenoit/kicbase:multiarch-2023-11-06`

Before exploring a custom fedora-based image, do you think we can contribute this fedora-based image in minikube or it'll always be a podman-desktop responsibility to maintain this image ?

**Comment by afbjorklund** [comment]
Currently the minikube container image is based on Ubuntu LTS, whereas the kind image is now based on Debian*.

\* since https://github.com/kubernetes-sigs/kind/commit/f3070ba86a9ae858ac4d5603bb1fec38dca91fe8

I don't think anyone is using Fedora for k8s, although one could imagine using something more stable like AlmaLinux.

Or somewhere inbetween, like CentOS?

----

But minikube already has a different OS image for the VM, and adding a third option to the test matrix is not ideal...

Even supporting something like podman or cri-o is distracting, since most users are running docker or containerd.

If it also requires a new OS, doubly so...

No chance of a Podman PPA, I take it ?

**Comment by benoitf** [comment]
ok, changed the title to make it part of a featured extension
