### ISSUE TITLE
Automate Podman Extension handling scenario

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#4795]
An automation of the #3789 E2E test scenario. Automate the test case on Linux and Windows environment.  Add the test into existing suite and make it run on PR check and On merge workflows.

**Comment by odockal** [comment]
We want the test scenario to be run on Linux and windows as now these are supported and available platforms from the CI perspective. 

Jobs on windows:
* https://github.com/containers/podman-desktop-e2e/actions/workflows/podman-nightly-e2e.yaml
* https://github.com/containers/podman-desktop-e2e/actions/workflows/podman-desktop-e2e-windows.yaml

Jobs on Linux:
* https://github.com/containers/podman-desktop/actions/workflows/e2e-main.yaml
* https://github.com/containers/podman-desktop/actions/workflows/pr-check.yaml (smoke e2e tests)

**Comment by ScrewTSW** [comment]
Tests on windows are failing because of https://github.com/containers/podman-desktop/issues/4593

![screenshot_20231207_151245](https://github.com/containers/podman-desktop/assets/16451875/1f13d5bc-affb-4be0-93bf-0ecad0860bb1)

Screenshot from artifacts doesn't contain anything usable, because the element is not visible on the screen (interaction through DOM, would have to scroll down to see it)

Examples of failed runs:
https://github.com/containers/podman-desktop-e2e/actions/runs/7124434492/job/19398670054
https://github.com/containers/podman-desktop-e2e/actions/runs/7124423630

**Comment by odockal** [comment]
Since the tests are passing on PR check and E2E tests main, we can close the issue. Thanks @ScrewTSW !
