### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5051]
- #5111 
 - #4118 
 - #5035
 - #5208

PRs to include:
 - #5145 
 - #5115
 - #5098
 - #4999
 - #5209
 - #5191 
 - #5182 

Possible candidates to include from post-1.6:
- #5219
- #5222
- https://github.com/redhat-developer/podman-desktop-demo/issues/33

**Comment by benoitf** [comment]
https://github.com/containers/podman-desktop/pull/5182 is a candidate as well

**Comment by feloy** [comment]
#5191 is candidate

**Comment by slemeur** [comment]
## Expected issues solved for 1.6.1
- #5216 
- #5129 & #5150 
- #5221 
- #5235 
- #5233 

### Expected from extensions
Not blocking the release - but will need to be fixed with releases of the extension
**DevSandbox**
- #5154 
**Minikube**


## PRs to be included in 1.6.1 branch (https://github.com/containers/podman-desktop/pull/5247)
- #5239
- #5240 
- #5248 
- #5246

**Comment by slemeur** [comment]
## Expected solved issues for 1.6.2
- #5254 
- #5258

PRs with backport to 1.6.2
https://github.com/containers/podman-desktop/pull/5260

**Comment by benoitf** [comment]
v1.6.3 is out
