### ISSUE TITLE
Flickering Zoom levels

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5265]
### Bug description

Zoom/resize problem when bouncing between chrome and podman desktop. You'll see in the video, I define a zoom level, I switch to chrome, I close podman desktop and sometime the zoom level is reset (either bigger or smaller).
I also have the same behavior happening when I resize the podman desktop window.
Happens with or without an external monitor.
Reproduced on Linux too

https://github.com/containers/podman-desktop/assets/1636769/eb2d7588-dfd3-4b2a-8d52-e6ad8939c22b

(see in the steps to reproduce the explanations about the video)

### Operating system

macOS 14.2.1
windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.6.0

### Steps to reproduce

- I start at normal zoom level (just the one when starting the app)
- I bounce between chrome and PD
- Then I close with the "closing app button" on mac
- _BUG1 (0:11 --> 0:24)_ Then I reopen it by going to the tray menu, dashboard --> **Here it automatically Zoomed In (probably 2 or 3 levels)**
- (0:24 --> 0:29) Then I'm zooming in with keyboard shortcut --> working fine
- (0:29 --> 0:40) Then I'm moving around in the app and it works fine
- _BUG2 (0:40 --> 0:42)_ I'm zooming out. **On the first press on the keyboard short cut, it is zooming out by 2 or 3 levels**
- (0:42 --> 1:12) I'm again bouncing between chrome and my environment. Things are going fine
- _BUG3 (1:12 --> 1:15)_ I'm now resizing my podman desktop window. And you can see that **the zoom level change while I'm resizing, but I'm not changing anything manually.**

**Comment by dgolovin** [comment]
Some tests I've done show the following does not help:
1. Using command line options for electron
2. Using <meta> tag viewport configurations
3. Using webContenst.setVisualZoom* and similar metods

I noticed it usually happens after navigating to `/images' page, until images page is not activated not zoom issues.

Commenting `router.mode.hash()` helps fix the issue when using left hand side navigation items, but then some links from inside of the pages can trigger unpredictable zoom again.  Also in this scenario reloading window from bar menu blanks main window because location is set to `file:///`.

Surprisingly if I add suffix `#top` to every `href` attribute and every `route.goto()` call the issue cannot be replicated, but that solution requires to fix 40 or so `goto` calls and Route.svelte implementation.

Second PR sent fixes the issue, but require to run static server on random port.

**Comment by dgolovin** [comment]
I can also replicate it on Windows 10
