### ISSUE TITLE
Service list: Display selector and list of endpoints

### ISSUE THREAD

**Issue by slemeur** [containers/podman-desktop#5367]
### Is your enhancement related to a problem? Please describe

Continuing and improving the work on https://github.com/containers/podman-desktop/pull/5363
 

### Describe the solution you'd like

Would be nice to display:
- the selector (what the user has defined)
- the list of endpoints, or at least the number of endpoints (what is the current state)

https://github.com/containers/podman-desktop/pull/5363#issuecomment-1867500019

**Comment by cdrage** [comment]
IMHO I believe we should move "selector" maybe underneath the service name / not in a column as there is too much information being shown at a time. With Podman Desktop being more developer-oriented rather than a full-featured Kubernetes dashboard, I believe we should consolidate information such as selector somewhere else.

Showing the list of endpoints though would be important (perhaps using the same "dots" as we do for Pods and having them green / red if they are up or down?). That's the first suggestion off the top of my head.
