### ISSUE TITLE
API: showInformation / showWarning / showError should allow markdown.

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5744]
### Is your enhancement related to a problem? Please describe

When I use the showInformation API, I would like to be able to pass in markdown.

For example, linking to an external document, or highlighting a certain part of the error message:

```ts
  const result = await extensionApi.window.showInformationMessage(
    `**WARNING!!** [Open this doc for more information](https://foobar.com).`,
    'Yes',
    'Cancel',
  );
  ```

### Describe the solution you'd like

Be able to pass in markdown to highlight messages / provide better dialog information.

**Comment by benoitf** [comment]
I think the current way to go is to have a 'More Info' button and the callback will open the URL

**Comment by axel7083** [comment]
I would really love to have markdown as we could make better display for example, if I want to display

`Are you sure you want to delete [something] ? The following files will be removed from disk - file 1 - file 2.`

The issue is, I can't force from an extension point of view, line return, so the message is a bit ugly.
