### ISSUE TITLE
Rework extend page of the website

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#5783]
### Is your enhancement related to a problem? Please describe

extend page is just a quick highlight

it should provide access to more content

### Describe the solution you'd like

provides access to some examples, API, howtos, etc

**Comment by axel7083** [comment]
@mairin you said in https://github.com/containers/podman-desktop/issues/5761 

> we could eventually have an online extension catalog here + a howto make your own extensiom area with dev docs

Do you think you might be able to make a makup for the extend pages ?

**Comment by mairin** [comment]
@axel7083 Yeh - it'll be lower on the queue since the website is less deadline sensitive but i can definitely take a look at this.

**Comment by cdrage** [comment]
https://podman-desktop.io/extend page right @benoitf ?

I'm assuming the best way to do this is to have it link to the https://podman-desktop.io/docs/extensions section.

I was thinking to update the images / have it simply point to https://podman-desktop.io/docs/extensions and expand that section since it will be done in https://github.com/containers/podman-desktop/issues/5782 anyways

**Comment by benoitf** [comment]
@cdrage yes correct it's about https://podman-desktop.io/extend

because it's basically saying we can extend but now we have more content to showcase
