### ISSUE TITLE
Investigate support for building quadlet files from pods.

### ISSUE THREAD

**Issue by sallyom** [containers/podman-desktop#5855]
### Is your enhancement related to a problem? Please describe

There is a lot of boilerplate configuration when creating quadlet files from pods, investigate whether desktop can generate quadlet files from container & pod definitions.
- list of images required by service
- quadlet.kube referencing a YAML
- quadlet.container with ports, mounts

### Describe the solution you'd like

I'd like desktop to offer a suggested quadlet for pod or containers.

**Comment by cdrage** [comment]
I've been using podlet to generate my files: https://github.com/k9withabone/podlet

You can generate a quadlet from a running container or even from `podman run -p 8080:8080 etc` commands using https://github.com/k9withabone/podlet

I'd be awesome to have this as an extension for Podman Desktop since it's a singular binary.

I only suggest this as whenever I've used the systemd generator tool built into podman there is always the large DEPRECATED notice.
