### ISSUE TITLE
Documentation: Categorize topics into similar folders

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#5883]
### Is your enhancement related to a problem? Please describe

Now that we have our documentation to be expanded 2-levels deep #5881 , there is a lot of documentation that should be categorized / more "hidden' / structured.

For example, these could be in a separate Kubernetes category:

![Screenshot 2024-02-06 at 10 20 11 AM](https://github.com/containers/podman-desktop/assets/6422176/32729f52-df66-4bb8-941a-66162bb17dd9)

Another is like this: 
 
![Screenshot 2024-02-06 at 10 21 55 AM](https://github.com/containers/podman-desktop/assets/6422176/3ecd6175-e509-4c77-9d89-58adbaa9b440)

Which could be in two sub-categories such as: Verifying or even 'macOS'

### Describe the solution you'd like

More sub-categories

**Comment by deboer-tim** [comment]
The first one is going to take some discussion, because there's both the marketing/discoverability aspect of it, and things like 'why are container engines top-level but not Kubernetes providers?'

For the second I'm not sure which ones you're referring to, but agreed that it looks like random topics and not clear where to start.

Maybe 'installation & configuration' should be one section, and include restricted environments?
