### ISSUE TITLE
Get events from containerEngine.onEvent when operations are done from CLI

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop#5892]
### Is your enhancement related to a problem? Please describe

When pods are stopped/started/created/deleted from the Podman Desktop GUI, an event is emitted by containerEngine.onEvent.

But when the same operations are done from the CLI (podman rm, ...), no event is emitted.

This is frustrating, as an extension would like to detect operations on pods, no matter if the user used the GUI or the CLI.

### Describe the solution you'd like

Get events for pods operations from both GUI and CLI.

**Comment by benoitf** [comment]
Do you have something to reproduce, because we're broadcasting the events that we receive from the container engine so there is no difference 'from the CLI' or 'from Podman Desktop'

it works as expected on my side. I receive in a modified podman extension the events that I can do from CLI

https://github.com/containers/podman-desktop/assets/436777/1b7c0994-850e-46c3-8902-370e5428e193

**Comment by benoitf** [comment]
my guess would be that your podman CLI is connected to another instance than your podman machine

**Comment by feloy** [comment]
> my guess would be that your podman CLI is connected to another instance than your podman machine

Yes you are right, after a new test, it works for me too.

Closing the issue. Thanks
