### ISSUE TITLE
Include a widget for recommended extensions at the bottom of the dashboard page.

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6215]
### Is your enhancement related to a problem? Please describe

subpart of https://github.com/containers/podman-desktop/issues/5771

Featured extension widget is nice but you just have short title/name and it's hard to know what it does

### Describe the solution you'd like

Add a banner to promote given extensions

it should be like featured extension but full-width widget with one extension at a time

### Edit (@axel7083)

- [x] #6656
- [x] https://github.com/containers/podman-desktop/issues/6669 
- [x] https://github.com/containers/podman-desktop/pull/6721
- [x] #6729

**Comment by axel7083** [comment]
To explain how the implementation could be made from my understanding of the requirements. We want to make a banner to promote one of the featured extension (while adding some visual elements to make it more appealing as we want it to be full-width).

Let's take the AI Lab mockup for this full width banner. 

(see penpot) 

From the mockup, we could make a basic layout and deconstruct it

![image](https://github.com/containers/podman-desktop/assets/42176370/9527faaf-6ff7-4035-8c83-b937ad047865)

In blue the elements that we need to provide in a new json, and in green the existing content that we can get **from the Featured class**.

Let's see a quick UML showing how this could be made

![image](https://github.com/containers/podman-desktop/assets/42176370/68019527-473f-488d-8f99-644d7c8f7805)

Just like the `Featured Extension` are managed by a class called `Featured`. We could create a `ExtensionBannerManager`, that would read the information we require (green) from a json file. A interface `ExtensionBanner` would be created, either extending the `FeatureExtension` interface or referencing one.

The reason behind #6656 is for the `ExtensionBannerManager` to be able to get all the featured extensions, to get the information required to create the banner. Currently, since it only return 6, we often not have the one we want in the list.

![image](https://github.com/containers/podman-desktop/assets/42176370/fa72e128-5e65-41d5-9291-9916fd03b6e8)
