### ISSUE TITLE
Onboarding: Windows - Global Onboarding is not resumed after required reboot (WSL2 installation)

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#6371]
### Bug description

![Podman_Desktop_DNr5zN9WVM](https://github.com/containers/podman-desktop/assets/16451875/1bfa0a23-c2cd-43be-adc3-9c61862fc03e)
Currently Global Onboarding is forcing a reboot after WSL2 requirement installation (makes sense, 100% valid)

However as a side-effect of this, some of the Global Onboarding is never executed on a fresh installation of Windows that was untouched by Podman or Podman Desktop in the past

After the reboot, only a "Podman needs to be set up" notification is shown in system tray, on which upon clicking the Dashboard is opened.
![Podman_Desktop_IfuiJIaEI5](https://github.com/containers/podman-desktop/assets/16451875/1134e95e-969c-48b5-9ee5-3084cdfa06e8)

User may resume onboarding individual items manually from there on, but in my opinion that pretty much defeats the purpose of Global Onboarding
![Podman_Desktop_3pknUHjGyQ](https://github.com/containers/podman-desktop/assets/16451875/d845e5ce-3529-4f14-a619-79f3b4e8e5a3)

I see this as a detrement to user experience. Input needed (PM/architect).

### Operating system

Windows 10, 22H2

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

Preparation:
* Clean up %HOME%/.local/share/containers
* Clean up %HOME%/.config/containers
* Clean up %AppData%/Local/Microsoft/WindowsApps
* Clean up %AppData%/Roaming/Podman\ Desktop/
* Properly uninstall WSL, Podman
* Disable WSL and Virtualization Platform

Onboarding:
* Download and run latest Windows installer
* Follow onboarding steps (manually enable Virtualization Platform /norestart)
* Click Install WSL2 button in Global Onboarding
* Perform required reboot

After restart:
* Podman needs to be set up notification is displayed in systray
* Upon clicking Dashboard is opened

### Additional context

**Comment by odockal** [comment]
Assuming that global onboarding in one-time on-startup thing, you have decided to skip it first, if assumptions are confirmed, then the behavior is alright, imho. If you choose to onboard kubectl, compose and podman, then podman is executed as the last and so the restart is fine since you have already onboarded the previous two.
Push up notification is only tied to podman and podman-machine.

**Comment by ScrewTSW** [comment]
> Assuming that global onboarding in one-time on-startup thing, you have decided to skip it first, if assumptions are confirmed, then the behavior is alright, imho. If you choose to onboard kubectl, compose and podman, then podman is executed as the last and so the restart is fine since you have already onboarded the previous two. Push up notification is only tied to podman and podman-machine.

Correct. I've missed the fact that docker-compose and kubectl are onboarded _before_ Podman which renders that part mute. My bad.

However, it still means that machine creation and podman configuration has to be triggered manually via the old approach - Onboarding/Dashboard

**Comment by benoitf** [comment]
I think that in case of reboot we could display again the global onboarding
(in case user didn't press any skip button)

**Comment by gastoner** [comment]
https://github.com/user-attachments/assets/a4ad6f69-c6f7-4789-a5a0-d127abaad90d


They had to change WSL behavior because the checkbox WSL feature does not work.
Running just `wsl --install` or `wsl --update` installs wsl and the restart is no longer needed (same behavior on Virtual Windows and on "classic" Windows) 


![Image](https://github.com/user-attachments/assets/778b7727-7f3b-4c74-8342-1aaa13240639)
^^ feature turned off but I've run `wsl --install` before

**Comment by ScrewTSW** [comment]
outdated
