### ISSUE TITLE
Different podman machine information displayed in PD compared to podman CLI on windows

### ISSUE THREAD

**Issue by cbr7** [containers/podman-desktop#6451]
### Bug description

It seems that when viewing the podman machine information, like allocated memory or disk space, Podman Desktop displays different values compared to what is seen in podman CLI.

![different_data](https://github.com/containers/podman-desktop/assets/106525396/50f21217-c9d8-4277-bbb8-2fcc72c85439)

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.8.0

### Steps to reproduce

1. Create a podman machine.
2. Go in PD to Settings -> Resources
3. View the information on the podman machine and compare it with the values from podman CLI
4. Notice that the values for memory and disk space are not the same.

**Comment by lstocchi** [comment]
I think this can be closed as the values displayed are correctly different. 
On the left it is the memory used, on the right the memory available (in green the one used). Same for disk. The cpus is the only value which has the same value. @benoitf WDYT?

**Comment by lstocchi** [comment]
@cbr7 are you referring to the fact that on the left you see 693MB and on the right 16GB of RAM, right?

**Comment by cbr7** [comment]
@lstocchi yes, and similar for disk size with 620 MiB vs 1 TB (which in itself is weird given that there there isn't 1 TB freely available on the whole HDD on my Mac). I assume the disk size it takes from the total size of the HDD on the Mac, but half of it is occupied.

**Comment by lstocchi** [comment]
On podman 5 i can see that the value printed out by `podman machine ls` are the max value available (at least on Win) so maybe it would make sense to show them. How about the Mac?

Currently the disk size value is calculated by using the graphRootAllocated and graphRootUsed which idk where they are calculated. The graphRootAllocated  seem to be a static value as i found other issues mentioning that 1TB on the podman repo (i have the same on Win). So either we show the same value as the `podman machine ls` but we won't have the usage donut or idk what else to show

**Comment by deboer-tim** [comment]
Not sure I follow, but is podman cli showing used memory on WSL but total memory on Mac? If so, that seems like a podman cli inconsistency/bug.

Podman Desktop appears to be consistently showing total memory with coloured arcs and tooltips showing how much is currently used, which is as designed. So it doesn't sound like we have an issue here unless it was confusing or there is a better way to show it. (although disk usage seems suspect in that first issue, would need follow up to see what was reported to us / why there is no arc)

**Comment by lstocchi** [comment]
@deboer-tim I got confused by the last message of @cbr7 as he mentioned Mac and i thought there was a problem on that too.

So to put clarity on this topic.

1 - On Mac (applehv) - the value are correctly displayed.

2 - on Windows (WSL) - after creating a machine, if i execute `podman machine ls` I can see the memory and disk size that i set when creating the machine. However, on WSL, the podman machine still rely on the host resources, so if i create a machine with 2 GB, it is actually using 16GB, the value that my host allows to use. The problem is the disk size which is calculated in an unknown way as i don't have 1tb of space. 

E.g. - If i create a machine with 14GB and 8 CPUs i can see these values on the cli
![image](https://github.com/containers/podman-desktop/assets/49404737/2adbbacb-b482-4cfc-b7a3-68c254d33587)
but on podman desktop
![image](https://github.com/containers/podman-desktop/assets/49404737/3b5f144d-59a4-42f5-80fe-e56e7fba2fd3)

3 - on Windows (Hyperv) - the data are in line with those used during the creation. If i create a machine with 3 cpus, 14GB of memory and 100GB of size.
from cli 
![image](https://github.com/containers/podman-desktop/assets/49404737/96b36119-0291-45e9-b0ce-da0a899dea18)

from desktop
![image](https://github.com/containers/podman-desktop/assets/49404737/0da34f6a-9712-4632-9ccb-5468a893d71d)


So the question is if we should do something regarding WSL - even though the values displayed are actually correct except the disk size. The cli is the one that shows "wrong" values

**Comment by lstocchi** [comment]
Opened https://github.com/containers/podman/issues/22816 . Closing this for the moment
