### ISSUE TITLE
'No Container Engine' on linux

### ISSUE THREAD

**Issue by JauntyJames** [containers/podman-desktop#656]
### Bug description

I have a working podman installation on Oracle Linux. I just installed podman-desktop via flatpak. On launch the home screen displays the 'Podman is Running' message. When I run any container via the podman command line they start up correctly, but none are listed in the podman-desktop application and it displays 'No Container Engine | Configure/Start a container engine first'

### Operating system

Oracle Linux Server release 8.6

### Version

0.8.0

**Comment by benoitf** [comment]
Hello @JauntyJames 
it may look like https://github.com/containers/podman-desktop/issues/459

Could you check if podman desktop has started the socket (or then manually launch the socket)

**Comment by JauntyJames** [comment]
@benoitf That's exactly it! The `--user` flag is what I needed in `systemctl --user start podman.socket`

**Comment by JauntyJames** [comment]
closing

**Comment by benoitf** [comment]
I'm reopening because Podman Desktop should start the socket on its own

**Comment by benoitf** [comment]
(or notify the user that there is something possible to do)

**Comment by dylanmtaylor** [comment]
Experiencing this bug on Ubuntu 22.04 using the Flatpak, with the podman package installed.

**Comment by benoitf** [comment]
@dylanmtaylor is that starting manually the socket is fixing the issue on your side ?

**Comment by dylanmtaylor** [comment]
After running systemctl --user start podman.socket, it works.

![image](https://user-images.githubusercontent.com/277927/197141946-e1f8a6d0-cd60-4831-88ac-b6740a558b83.png)

Unrelated, is it intentional for this app to have a menu bar? It looks really out of place here, compared to native GTK 4 apps in GNOME, and doesn't seem to provide much/any functionality you can't perform otherwise.

**Comment by benoitf** [comment]
@dylanmtaylor I think the menu bar is there because on Windows and macOS there is a tray icon visible but on Gnome users need to install 3rd party tools to view tray icons. So it's mainly why the menu is there.

Of course, it can be revisited, we could add options to disable it, etc.
The best way to discuss it is to file a new issue and let's discuss on the issue.

**Comment by dylanmtaylor** [comment]
> Of course, it can be revisited, we could add options to disable it, etc. The best way to discuss it is to file a new issue and let's discuss on the issue.

Good call. I just opened https://github.com/containers/podman-desktop/issues/663

**Comment by J3RN** [comment]
I'm also experiencing the issue where Podman Desktop does not start the podman socket on its own; requires me to start the socket manually (but works fine after that point).

Fedora Silverblue 36, installed Podman Desktop as a flatpak through Gnome Software.

**Comment by benoitf** [comment]
thanks @J3RN for the report
Always helpful to have reports with the version of the OS

I'll need to look at the issue more deeply

**Comment by LenzGr** [comment]
Just came here to report the same. Installed and started Podman Desktop 0.9.0 via flatpak on Fedora 36 where I used podman 4.2.1 on the command line before successfully.

The startup log printed actually points out that the socket could not be found, but it's not really emphasized as an error:
```
 Could not find podman socket at /home/lenz/.lima/podman-lima/sock/podman.sock nor /home/lenz/.lima/podman-lima/sock/podman.sock
```
The Dashboard shows "Podman is running", but all other pages (Containers/Images/Pods/Volumes) just state "No Container Engine - Configure/Start a container engine first", without any obvious option on how to accomplish this. I ended up trawling the entire UI and Settings page without any resolution, so this turned out to be a somewhat negative first user experience.

If the application fails to create the socket by itself, but it is essential for it's functionality, it should either abort with a clear error or provide some useful guidance on how to resolve this (e.g. via a short help text in the app or via pointing to the Troubleshooting section in the docs). Currently, an inexperienced user gets stuck here.

**Comment by benoitf** [comment]
Hello, I tried using Ubuntu 22 or Fedora and Fedora Silver blue but it always worked for me without doing any other extra step
![image](https://user-images.githubusercontent.com/436777/199981508-f98f95ef-69a5-487d-b1e2-963702ab58a5.png)

so I might be interesting in how people that experienced issue installed the flatpak.

also when running Podman Desktop, it spawns a `podman system service --time=0` command

Are you able to check that this process is running and if so, under which username ?
And this command is providing the link to the socket 

![image](https://user-images.githubusercontent.com/436777/199982298-39c23279-909a-4a56-87f0-a879d77d9e73.png)

so I would need to know if the command is launched, if the command is creating the file as expected or your system ?

**Comment by J3RN** [comment]
After starting Podman Desktop, I have the `podman.sock` file and *three* `podman system service --time-0` commands running, one of which is using `flatpak-spawn`:

![image](https://user-images.githubusercontent.com/2058614/200044366-9e64c803-f851-41f6-bb83-9b5754fa1f19.png)

**Comment by J3RN** [comment]
On a fresh login, I have neither
![image](https://user-images.githubusercontent.com/2058614/200044983-09adc1b3-0f84-459d-89a4-03c0bf4755bd.png)

**Comment by J3RN** [comment]
I just discovered something rather odd: When I first start Podman Desktop, it doesn't detect the container runtime, but if I quit it (File -> Quit) and restart it, it works as intended:
![image](https://user-images.githubusercontent.com/2058614/200045747-fe34a0a6-c23b-49bd-a2ba-14f3a2fb276d.png)

**Comment by benoitf** [comment]
Ok so probably Podman system service is taking too long to add the socket 
Need to wait longer / check for the file

Thanks for the hints

**Comment by benoitf** [comment]
@J3RN if you're able to test artifacts from https://github.com/containers/podman-desktop/actions/runs/3409026816 (build from Pull Request https://github.com/containers/podman-desktop/pull/784)

Please ensure that no 'podman system' processes are running and that `/run/user/1000/podman/podman.sock` does not exists (or remove it)

**Comment by J3RN** [comment]
Sorry for the delay!  I downloaded that test artifact and tried it.  Podman Desktop now hangs for a few seconds displaying the work "Initializing", but then loads with the same error as before.
![Podman Desktop now hangs for a few seconds displaying the work "Initializing", but then loads with the same error as before.](https://user-images.githubusercontent.com/2058614/201979535-2e75a839-8bfc-421d-b871-483a696730bb.gif)

**Comment by themr0c** [comment]
I could reproduce the issue at will as following:

```
pkill flatpak-spawn ; rmdir /run/user/1000/podman/ ; flatpak run io.podman_desktop.PodmanDesktop/x86_64/main
```
