### ISSUE TITLE
Opening a webview within podman desktop from the app built in development mode shows empty screen

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#6740]
### Bug description

When trying to open a webview from a podman desktop taht is run from e2e tests (podman desktop is built in development mode) I got only a black or empty screen.

### Operating system

Fedora 39

### Installation Method

Other

### Version

next (development version)

### Additional context

When opening the webview from a flatpak installed podman desktop, it opens up, but I see an error in the console:
```
Uncaught Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at EventEmitter.emit (VM4 sandbox_bundle:2:34768)
    at Object.send (<anonymous>:2:328)
    at IpcRenderer.<anonymous> (<anonymous>:2:720)
    at IpcRenderer.emit (VM4 sandbox_bundle:2:34768)
    at Object.onMessage (VM4 sandbox_bundle:2:50712)
```

**Comment by cbr7** [comment]
![webview_error](https://github.com/containers/podman-desktop/assets/106525396/833e578d-b554-453c-9b59-aa889b0c972b)

I'm not sure if it's related or not, but I've added a screenshot of a warning from the webview console, where the same file `VM4_sandbox_bundle` is referenced as in the error from the main PD console.

Is it possible that some kind of security policy is preventing the dom-ready event from being emitted?

**Comment by odockal** [comment]
@cbr7 TBH I have not seen the dom-ready not being omitted error when running the developer mode at all. Or it is that error is actually consumed somewhere?
I tried to debug the application and found a difference between running in dev mode and the one built locally, but I do not see exact point of failure.

I suspect that there might not be a problem on podman-desktop side, might be in the extension and how it takes over meta variable. Or maybe the problem lays somewhere around http server that should take care of dom elements recreation on podman desktop side. Server is running, I just do not know if it receives the request and if responds anything. I am just judging as there is missing iframe dom element in the dom structure once the button is clicked in podman-desktop devleopment mode.

**Comment by odockal** [comment]
Reproducer on my branch: https://github.com/odockal/podman-desktop/tree/webview-repro
```
git clone git@github.com:odockal/podman-desktop.git
# git remote add odockal git@github.com:odockal/podman-desktop.git
git fetch odockal
git checkout odockal/webview-repro

yarn
# test:e2e build podman-desktop locally in dev mode
# once you have it built, you can re-run e2e tests faster by using test:e2e:run
yarn test:e2e
# yarn test:e2e:run
```
The tests contain only one e2e tests (`tests/playwright/src/specs/bootc-extension.spec.ts`) that will spin up podman-desktop in dev mode, and installs bootc extension. Then there is a a hard coded timeout at line 88. which will wait a minute for exploration. can be adjusted of course, the test itself has 200s hard limit, can also be adjusted.
Once the extension is installed, bootc nav bar item appears, if you click it you would expect bootc webview to be shows. It is not.

**Comment by axel7083** [comment]
Following my investigation here are my results

## `webview-preload.ts`

Let's deep dive into the preload script, which is the one responsible of reloading the content when the extension update its html.

I added 3 `console.log` visible when running through in `yarn watch`
![image](https://github.com/containers/podman-desktop/assets/42176370/2831a5eb-7083-4cbc-8d5b-fb05c0fe2436)

However when running with `yarn test:e2e` nothing appears in the console.log

![image](https://github.com/containers/podman-desktop/assets/42176370/75637728-36c5-4c90-a07a-db1d17573f37)

The preload script does not seems to be working and that seems to be the source of the problem.

To verify that the content of a webview/iframe could be visible from playwrite, I replaced the following lines

https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/main/src/plugin/webview/webview-registry.ts#L122-L125

> ℹ️ the code above, send the default content to the webview, before the extension is able to change it.

with some html with identifiable content

```html
<html style="color: white;">
  <div role="banner" aria-label="banner that should be removed">
      Hello from webview (this should be removed after preload)
  </div>
</html>
```

And during the test:e2e I got the following as expected
![image](https://github.com/containers/podman-desktop/assets/42176370/6e505dc9-c38f-498f-b7af-f0af34bc954b)

Then through the following code I was able to ensure the _banner_ hardcoded was visible by playwright

````ts
const iframes = pdRunner.getElectronApp().windows().map(window => window.frames()).flat();
for (const iframe of iframes) {
  const count = await iframe.page().getByRole('banner', { name: 'banner that should be removed'}).count();
  console.log(`iframe ${iframe.url()} => ${count}`);
}
````

output:

````ts
stdout | tests/playwright/src/specs/bootc-extension.spec.ts > BootC Extension > Open webview
iframe file:///C:/Users/axels/Documents/github/redhat/podman-desktop/packages/renderer/dist/index.html#/webviews/0 => 0

stdout | tests/playwright/src/specs/bootc-extension.spec.ts > BootC Extension > Open webview
iframe about:blank => 0

stdout | tests/playwright/src/specs/bootc-extension.spec.ts > BootC Extension > Open webview                                                                                                                                        
iframe http://7304a1bd-1199-4e37-9ac3-054095428031.webview.localhost:44000/?webviewId=0 => 1 
````

We can clearly see in the last one, that we got the expected Locator based on the role and aria label.

## Conclusion

Even tho I am not able to understand why the preload script is not loaded when using the `yarn test:e2e` IMO the issue is coming from Podman Desktop and not Playwright.

**Comment by odockal** [comment]
@axel7083 Awesome work here!
After narrowing down the possible places of issue, it seems that having webview-preload init function being only available when not having VITEST set is the root cause of webview not being available in development mode. 
Removing the if block here: https://github.com/containers/podman-desktop/blob/main/packages/preload-webview/src/index.ts#L39 let the webview to load correctly when running e2e tests.
We need to make sure that init function is available when running e2e tests.

**Comment by benoitf** [comment]
good investigation work 👍

**Comment by benoitf** [comment]
@odockal I don't know why I'm the assignee here, I didn't do stuff

**Comment by odockal** [comment]
@benoitf you did a fix, right? :)

**Comment by benoitf** [comment]
fixed by https://github.com/containers/podman-desktop/pull/6842
