### ISSUE TITLE
review current design of Extensions workflow

### ISSUE THREAD

**Issue by benoitf** [containers/podman-desktop#6757]
### Is your enhancement related to a problem? Please describe

here are screenshots of updated implementation of the extensions page to iterate / gather ideas 

It should ordered by priority like:

- must have before being merged
- need follow-up as it's still better than what we have so we can't hold for a while
- potential increment

### Describe the solution you'd like

Collect feedback / options

for example some people dislike the redundancy of the word 'extension', start/stop could be activate/deactivate or enable/disable
replace DD extension label by `Docker Extension`

bigger icons for extensions, removal of some content, adding description of the extension

in extension detail page, background color of the sidebar, scrollbar, etc

here are the screenshots:

- Extension List:
![image](https://github.com/containers/podman-desktop/assets/436777/13d66794-33e2-4227-ac43-18d3700265d1)

- Extension List filtering
![image](https://github.com/containers/podman-desktop/assets/436777/1221f00f-06ae-4f8f-a88f-c16491117336)

- Extension Details
![image](https://github.com/containers/podman-desktop/assets/436777/3d003d10-06a5-43cc-8a12-79c15f6b57ba)

- Extension Catalog
![image](https://github.com/containers/podman-desktop/assets/436777/d9243dbb-e179-4c1b-b784-cdd7d9f68d2a)

- Custom Install
![image](https://github.com/containers/podman-desktop/assets/436777/f3568ef2-fb74-4d9d-b65e-27ff0b6548db)

![image](https://github.com/containers/podman-desktop/assets/436777/db9f18bd-9461-436c-b887-04387d8e60ae)

**Comment by vzhukovs** [comment]
One of the most potentially motivating things to the users will be an additional button near `Install Custom...` called `Create Own` or `Develop an Extension`, that will generate the skeleton of the empty extension or the simple one, like hello world. From what I see, we're missing such things. We have the ability to install an extension, but there is no information how to develop them on the UI. Could be useful I think.

**Comment by axel7083** [comment]
That's a lot of work, it is already such an impressive upgrade 👍 ! I have some comments, based mostly on how I feel with the implementation. (Nothing I listed is a necessity and falls under the `need follow-up as it's still better than what we have so we can't hold for a while`)

## **Navigation**

![image](https://github.com/containers/podman-desktop/assets/42176370/a50a9c5b-8227-47b2-8174-675ac3a375f2)

IMO the `Puzzle` icon should be at the bottom as it is more a settings/configuration items rather than a resource or utility.

## **Extension List**

The choice of the icons feel odds to me. 

- `Setting Gear` for onBoarding 
- `Paper Edit` for opening preferences

I would have something like a rocket or even a plane, to really show the action of on boarding

| Rocket | Plane |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop/assets/42176370/c91b4788-3e3d-42e8-9c51-38775b63ee69) | ![image](https://github.com/containers/podman-desktop/assets/42176370/ea1e879f-5658-4eba-a2ca-cb851abaf746) |

I have some issue with the actions button, as the `settings` (gear) is disabled, I would not show it if the action is not available. Also to use the spaces available, I would have placed it at the top right of the card. 

The different design buttons grouped all together feel very weird to me. 

| Extension | Resource |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop/assets/42176370/9661cd52-c92a-4fd1-9bcf-b8d876722949) | ![image](https://github.com/containers/podman-desktop/assets/42176370/6cbdbfd8-77a6-44a2-8b15-732ab0bbd8c2) |

The open details icon also feel strange, as it should be on the right to keep the consistency with the resource page

## **Extension Details**

I do not really like the extension details, as I have a feeling that the layout is not consistent with the application, having a scrolling container in the middle with some informations sticking on the right feel odds...

I am taking the JetBrain Plugin page as an example here

![image](https://github.com/containers/podman-desktop/assets/42176370/a80d377b-4968-4039-ad9d-f81c9d28291b)

I am wondering if we should not move the version and author to the top, then they will still stick to the top, without having this weird (IMO) card on the right, which is not really bringing much information in reality.

Moreover, if we really want a dedicated places for more information, tabs could be a solution, as shown in the JetBrain example.

## **Custom Install**

Maybe the placeholder's input should not be the place with all the details, and have some text above to give some details ?

## **Extension Catalog**

![image](https://github.com/containers/podman-desktop/assets/42176370/140a4bbb-7230-4ffb-850f-326c79daf3a0)

The card layout feel too big, why so much unused spaces ?

![image](https://github.com/containers/podman-desktop/assets/42176370/ec22e523-6bc3-4f79-8e9c-b0872f53498c)

Why do we use a header here `Available extensions` when we do not have one for the Installed one? I think we could remove it, as it does not bring a lot of information, since we already are in the `Catalog` tab, meaning that it is listing the available one

**Comment by axel7083** [comment]
@benoitf can we close ?
