### ISSUE TITLE
bug(NavApplication): ids are not unique for docker extension 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#6846]
### Bug description

As explained in https://github.com/containers/podman-desktop/pull/6835#issuecomment-2068869331 we could face some problems when multiple extensions have the same id.

### Operating system

any

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

### Steps to reproduce

> install both aquasec/trivy-docker-extension and redhatdeveloper/openshift-dd-ext as Docker Desktop extensions

**Comment by deboer-tim** [comment]
After updating to include #6835 the main nav was completely broken for me - items were missing and I couldn't navigate to any of the pages like Containers that were there. Traced it back to having 2 DD extensions installed and deleting them got around this.

An average user would not be able to figure out what the problem is so I tagged this for milestone 1.10 - either we need to fix this or back out the previous change.
