### ISSUE TITLE
Implement Spinner UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6897]

**Comment by axel7083** [comment]
Migrating the spinner is kinda annoying because of the following line 

https://github.com/containers/podman-desktop/blob/695c9ea95787c52d38518246d1e77d166c94c137/packages/renderer/src/lib/markdown/micromark-button-directive.ts#L21

In this line we are getting the raw content, (aka source code) of the `Spinner.svelte` file.

However, once in the `@podman-desktop/ui-svelte` it gets complicated to do the same.

Looking at the `@podman-desktop/ui-svelte` content. We have a `dist` folder with the expected `spinner/Spinner.svelte` file, however I am not able to get it imported.

I tried to replicate the behaviour of tinro, by adding 

```
optimizeDeps: {
  exclude: ['tinro', '@podman-desktop/ui-svelte'],
},
```

to the vite config of the renderer.

add `declare module '@podman-desktop/ui-svelte/dist/spinner/Spinner.svelte';` to the `types/additional.d.ts` file.

and tried to import with the following `import spinnerSourcecode from '@podman-desktop/ui-svelte/dist/spinner/Spinner.svelte?raw';`
