### ISSUE TITLE
Implement MarkdownRenderer UI component

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#6900]

**Comment by axel7083** [comment]
I would not add the MarkdownRenderer to the podman ui library as it is an entire package on its own; in ai-lab we are not using the same as podman because it was not providing enough customization for our usage (from my memory). I would not include this, and would also recommend a third party package such as svelte-markdown

**Comment by axel7083** [comment]
I still believe we should keep the ui library dependency free, and not add third party package in it such as markdown. If webview wants to use markdown, they can yarn install one of the many existing available markdown package.

Waiting for @jeffmaury confirmation to close

**Comment by axel7083** [comment]
Closing it as will not be implemented
