### ISSUE TITLE
Authentication menu: propose extension if no provider is installed

### ISSUE THREAD

**Issue by vrothberg** [containers/podman-desktop#6911]
### Is your enhancement related to a problem? Please describe

When no authentication extension is installed, the Authentication page proposes to install one but it's unclear which ones to install.  Maybe the page can propose some directly to improve the UX?

![Screenshot 2024-04-24 at 11 16 31](https://github.com/containers/podman-desktop/assets/11679875/38e2617b-591b-4fc7-898a-0507dc7def87)

### Describe the solution you'd like

![Screenshot 2024-04-24 at 11 16 31](https://github.com/containers/podman-desktop/assets/11679875/e4663838-bed8-446f-ba33-44086d01f78c)

**Comment by deboer-tim** [comment]
The extension catalog already has categories like `"categories": ["Authentication"]`. We could create an embeddable catalog component that would filter to a specific category, or a far quicker option would just have a link here that opens the existing Catalog page with 'Authentication' typed in.

Design should weigh in, since it is not just about dev cost but whether it's better to have an embedded experience or to reinforce where users should go to install other things in the future.

**Comment by vrothberg** [comment]
> The extension catalog already has categories like "categories": ["Authentication"]. We could create an embeddable catalog component that would filter to a specific category, or a far quicker option would just have a link here that opens the existing Catalog page with 'Authentication' typed in.

Love that idea.  Let's wait for more feedback :)

**Comment by benoitf** [comment]
created https://github.com/containers/podman-desktop/pull/6936 and https://github.com/containers/podman-desktop/pull/6935
