### ISSUE TITLE
"Only show running containers" filter for containers

### ISSUE THREAD

**Issue by dylanmtaylor** [containers/podman-desktop#707]
### Is your enhancement related to a problem? Please describe

Docker desktop has a feature where you can choose to filter the list of containers to show only the running ones. If it has none, it will show "No running containers". I'd like to see this feature for Podman desktop.

### Describe the solution you'd like

Add a toggle to the right of the search bar in the containers tab to allow users to filter on the running status. Only show running containers in the list.

**Comment by Dogacel** [comment]
This is very crucial for me, it makes the transition from another container manager very though without this feature.

**Comment by feloy** [comment]
![containerlist](https://github.com/containers/podman-desktop/assets/9973512/dd52b196-030c-4f93-9a11-ce099bb0e029)

Hi @mairin could you confirm this is the way we want to display the list of running/stopped containers, using tabs?

**Comment by mairin** [comment]
@feloy to document here for @Dogacel, we talked about this in chat a day or two ago and I confirmed that the tabs are the way to go :)

@Dogacel if you are in Discord or Matrix I'd love to talk to you about your use case, let me know.

**Comment by Dogacel** [comment]
> @feloy to document here for @Dogacel, we talked about this in chat a day or two ago and I confirmed that the tabs are the way to go :)
> 
> @Dogacel if you are in Discord or Matrix I'd love to talk to you about your use case, let me know.

Sure, I am on Discord with the same handle, `Dogacel`.

My use-case is actually pretty simple, we are creating lots of containers throughout the day that are temporary and they are making the container tab look very crowded. We have a couple important ones such as Database container which we use daily. It makes it though to navigate and find which containers we have running right now as well.

We are moving away from Docker Desktop, that was an available future in containers tab as a toggle and I always kept it on. Currently we couldn't use podman engine because some of our workflows depended on `Ryuk` so we are using Lima, which supposedly should work with Podman Desktop but I couldn't make it work so I don't have any screenshots 😢 .
