### ISSUE TITLE
Containers kebab menu is partially hidden when opened in narrowed window

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7321]
### Bug description

![Screenshot_20240528_084856](https://github.com/containers/podman-desktop/assets/19164299/0e8a8f49-30ab-4ccf-8749-bbd98ea5ab60)

### Operating system

Fedora 40

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

**Comment by deboer-tim** [comment]
This issue has been there for a while - NavPage uses overflow-auto to trigger scrolling content correctly, and I moved it from each of the individual pages to NavPage last June [1], so it has been a problem at least that long. (not saying we shouldn't fix, just that it's not a recent regression)

[1] https://github.com/containers/podman-desktop/commit/01c4d97fd27b217551e1624655300f692926fb40

**Comment by axel7083** [comment]
Okey the problem is very annoying.

The dropdown decide by itself to be positioned on top or bellow the click event with the following logic

https://github.com/containers/podman-desktop/blob/88907772c08058ac7bb91a79e9afec367f43ca75/packages/ui/src/lib/dropdownMenu/DropDownMenuItems.svelte#L14-L15

The content of the page, has an `overflow-auto` which is required to make the page scrollable.

![image](https://github.com/containers/podman-desktop/assets/42176370/491d5f03-0f56-41ba-9cff-dd5d11707ae7)

The only solution I can see is to **always** put the dropdown on the bottom, the scrolling will automatically handle it.

https://github.com/containers/podman-desktop/assets/42176370/bb87ecf1-0e48-4d33-ad36-b576f8b64019

cc @deboer-tim any opinion ?

**Comment by deboer-tim** [comment]
I think we're going to need to use tricks with z-order instead of overflow-hidden for the page header, maybe even titlebar/navbar/statusbar so that popup menus can go over top of these areas instead of being cutoff - but that's going to be complicated so I agree just switching to bottom is a much faster/simpler fix at the moment.

**Comment by axel7083** [comment]
https://github.com/containers/podman-desktop/pull/7995 fixed the issue, thanks @deboer-tim :)

https://github.com/user-attachments/assets/05f4c429-66a5-4784-adaf-647ee9ed0c37
