### ISSUE TITLE
Form page shadow doesn't extend past header

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman-desktop#7549]
### Bug description

The shadow that should extend down the full left column is only in the header for form pages, including Help, Troubleshooting, Build, etc.

Including screen cap from light mode as it is much more obvious:
<img width="241" alt="Screenshot 2024-06-10 at 10 15 20 AM" src="https://github.com/containers/podman-desktop/assets/19958075/5703b2e6-c709-496a-aed8-895a8233dc5e">

### Operating system

macOS 14.5

### Installation Method

None

### Version

next (development version)

**Comment by axel7083** [comment]
After some investigation, the problem is that the shadown is created by the parent component here `FormPage.svelte`.

https://github.com/containers/podman-desktop/blob/f25dc1befb7a87a5ae688d60c58f4c70819c93ad/packages/ui/src/lib/layouts/FormPage.svelte#L37

But lower in the hierarchy, it define the background color, overlapping the shadow

https://github.com/containers/podman-desktop/blob/f25dc1befb7a87a5ae688d60c58f4c70819c93ad/packages/ui/src/lib/layouts/FormPage.svelte#L82

## Possible solution

### Absolute shadow

We could add `<div class="z-50 shadow-pageheader w-full h-full absolute"/>` inside the FormPage, which would create a shadown overlay, solving the problem.

![image](https://github.com/containers/podman-desktop/assets/42176370/bd33b210-7b8e-4def-af5c-51f1b5f69dab)

### Make the FormPage background the same as the content

We seems to already use the same color for the header and content, let's define it next to the shadown.

Same result

![image](https://github.com/containers/podman-desktop/assets/42176370/a5cbead8-9c96-49c4-bc9c-2bd52a9b3fe9)

cc @feloy @deboer-tim

**Comment by deboer-tim** [comment]
These used to have different colors for header and content, which is probably why there was a distinction so we didn't notice this issue. @ekidneyrh changed to use a single color in forms when @feloy was implementing light mode here, so my preference is the last option. I think we need to remove the 1px horizontal line too, it just looks out of place now.
