### ISSUE TITLE
Add stop button to the app

### ISSUE THREAD

**Issue by hguerrero** [containers/podman-desktop#755]
### Is your enhancement related to a problem? Please describe

There is no easy way to stop the podman machine similar to how we start it.

### Describe the solution you'd like

Keep the switch to start and stop the podman machine.

**Comment by benoitf** [comment]
Thanks for this another report.

There is way but we're working on making it more obvious.

If you go to the preferences/settings page, you can find in `Resources` all machines (and then start/stop them)

**Comment by benoitf** [comment]
![image](https://user-images.githubusercontent.com/436777/199537692-d4de9343-c07d-45a8-910f-6a8dc2eaf826.png)

**Comment by hguerrero** [comment]
I see, my concern is that the _Home_ page shows this:

![image](https://user-images.githubusercontent.com/1001939/199565038-801416fa-750e-4382-a186-3279c4d4e960.png)

Where the UI element is a switch. After clicking on it, it disappears, and there is no way to interact with it anymore.

![image](https://user-images.githubusercontent.com/1001939/199565431-74ddd1b2-32d9-49bf-b814-3dbdeffe0ea4.png)

Should that element be a button instead?

**Comment by deboer-tim** [comment]
We have gone through a lot of UI design and updates since November, and while there is more coming the intent is starting to become more clear: future onboarding and the dashboard are meant to help users get started and notifications, but we won't be exposing everything here. The Settings > Resources page will show everything that you've installed and allow you to start/stop/delete (i.e. manage) them.

Please take a look at a recent install. If there's anything you still think we need to address please feel free to open issues based on the current design.
