### ISSUE TITLE
Images list not updated when manifest created from CLI

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#7606]
### Bug description

Create a manifest using podman manifest create and images page is not updated

### Operating system

Win11Pro

### Installation Method

None

### Version

next (development version)

**Comment by cdrage** [comment]
I am unable to replicate @jeffmaury 

I did the following:

```sh
git clone https://github.com/cdrage/containerfiles
cd helloworld
podman build --platform=linux/arm64,linux/amd64 --manifest foobar .
 ```
 
 I also created a blank manifest with no child images and it also appears:
 
 ```sh
 podman manifest create test123
 ```
 
And it is appearing in the image list:
![Screenshot 2024-06-12 at 12 12 04 PM](https://github.com/containers/podman-desktop/assets/6422176/e5aecbf8-54d2-4dcf-8b90-93dcfd0f5036)

**Comment by cdrage** [comment]
So I figured out why it's not working, and its an intentional feature:

In your Containerfile, you will have to add other steps, for example, if you do:

```Dockerfile
FROM quay.io/ai-lab/llamacpp_python
```

and build it, it will not appear:
```
▶ podman image ls
REPOSITORY                      TAG         IMAGE ID      CREATED        SIZE
localhost/test1                 latest      9c79e65baf98  9 seconds ago  1.25 kB
```

This is because `quay.io/ai-lab/llamacpp_python` already have both architectures hosted, so it does not make child images. It's intentional and shows in `podman image ls` with no child images.

However if you add something like:

```
FROM quay.io/ai-lab/llamacpp_python
RUN echo "foobar" > /tmp/test123.txt
```

It will appear as it's built the child images based on the `quay.io/ai-lab/llamacpp_python` arm / amd base images:

```
▶ podman image ls
REPOSITORY                      TAG         IMAGE ID      CREATED         SIZE
localhost/test2                 latest      dd609dd05a01  11 seconds ago  1.23 kB
<none>                          <none>      7bfc8d98a2f4  12 seconds ago  1.49 GB
<none>                          <none>      de4a56f0a222  14 seconds ago  1.51 GB
```

**Comment by cdrage** [comment]
Going to close this as this is an upstream issue  as when used directly on the CLI it does not create the child images if nothing else in the Containerfile exists other than FROM. Which would be intentional as there are no other layers being created.
