### ISSUE TITLE
Initializing stuck

### ISSUE THREAD

**Issue by ashimov** [containers/podman-desktop#7611]
### Bug description

![image](https://github.com/containers/podman-desktop/assets/9959703/7ea345c6-9c68-4c11-80d8-052b6e328e06)

### Operating system

MacOS Sonoma 14.5(M3 Pro)

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

**Comment by odockal** [comment]
@feloy Do you think that you could try to reproduce this one?

**Comment by feloy** [comment]
@ashimov are you running the app from inside a corporate network? An air-gapped one?

**Comment by ashimov** [comment]
> @ashimov are you running the app from inside a corporate network? An air-gapped one?

Hi!I'm running inside a corporate network with router & without any next-gen firewall's

**Comment by feloy** [comment]
> > @ashimov are you running the app from inside a corporate network? An air-gapped one?
> 
> Hi!I'm running inside a corporate network with router & without any next-gen firewall's

Hi @ashimov, I have a few more questions:

- could you try to install the air-gap version (by downloading [podman-desktop-airgap-1.10.3-arm64.dmg](https://github.com/containers/podman-desktop/releases/download/v1.10.3/podman-desktop-airgap-1.10.3-arm64.dmg))?
- Would you have the possibility to try to execute it from a non-corporate network, to check if the issue comes from some network connectivity?
- were you able to start the application successfully before, or did you get this Initialization screen every time you tried to execute it?
- do you have some specific software on your machine which could limit access to some system resources? (if your computer is managed by your company for example)

**Comment by feloy** [comment]
@ashimov, did you have the opportunity to check the different points I provided above? To test with the newer releases of Podman Desktop?

**Comment by odockal** [comment]
@ashimov Did you have any chance to try newer version?

**Comment by feloy** [comment]
Closing as there is no feedback from user
