### ISSUE TITLE
Container table age column will not display `Starting...` `Stopping..`

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7734]
### Is your enhancement related to a problem? Please describe

As requested by @cdrage in https://github.com/containers/podman-desktop/pull/7725#issuecomment-2176759970 with this PR merged, the age column will only show duration (as it should).

Meaning we will stop showing the `Starting...` and `Stopping...` text in this column

This is not really a problem has we already show this in another place

![image](https://github.com/containers/podman-desktop/assets/42176370/1d0c42a7-b4c6-48a8-9f3e-58b4b15c3f2f)

### Describe the solution you'd like

https://github.com/containers/podman-desktop/pull/7725 merged

**Comment by cdrage** [comment]
@ekidneyrh

**Comment by deboer-tim** [comment]
Thanks for opening @axel7083. As per my comment in 7725, the Starting... and Stopping... in this column was originally a UX suggestion for both Containers and Pods pages to make the state change more obvious (you clicked a button and something is now happening). In the Pods case we don't have the text in the Name column, but in my opinion both are somewhat random (why is state in Name column or state change in Age, and when we also have a Status column?), and worse because we don't do them in any other pages.

IMHO we should have a minor UX decision on whether we need to show the state text anywhere other than the Status column/tooltip, and ditto for state _changes_, and then make things consistent on all pages. But personally I'd be fine if we just removed from Pods as well and deleted StateChange.

**Comment by ekidneyrh** [comment]
I think it's good to have that feedback that something is happening, so along as something changes somewhere it's fine by me to remove the starting and stopping from the age

**Comment by axel7083** [comment]
Closing as confirmed we do not need it anymore
