### ISSUE TITLE
Validation of the custom port mapping in the Run Image page is not reset when value is corrected and prevents container to be created

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#7812]
### Bug description

Validation of the custom port mapping is not reset when error is shown (ie, using non existent port number) and the start container button is not reenabled when port number corrected or custom port mapping field removed.

User needs to leave the page and start over.

### Operating system

Any

### Installation Method

Installer from website/GitHub releases

### Version

next (development version)

**Comment by lstocchi** [comment]
@odockal not sure if i misunderstood the problem or it was fixed in the meantime but it works fine imo.
If i fix the port, the error disappears and the button is enabled again
![runimage_error](https://github.com/containers/podman-desktop/assets/49404737/64323584-092f-4978-bfa8-46dbe648ad50)

**Comment by odockal** [comment]
@lstocchi Keep the wrong port number (with validation error), remove the port mapping by clicking on minus sign on the right. You are stuck.

**Comment by odockal** [comment]
Also, another case is when you type in wrong port number, select the value and delete it. The validation still shows error and button is not enabled.

**Comment by lstocchi** [comment]
@odockal ah great, thanks!! I'll try it 👍

**Comment by lstocchi** [comment]
@odockal i was able to replicate it.

Regarding the second use case i'm a bit hesitant to do something bc the error displayed actually changes and it is clear what it is expected by the user. Before there was a port, now it's empty but the user is expected to add a valid port, otherwise just remove the entry.
![image](https://github.com/containers/podman-desktop/assets/49404737/0559990a-2513-4134-8541-51ad52ed540c)

**Comment by odockal** [comment]
@lstocchi You are right there. Thanks!
