### ISSUE TITLE
Add the link to the release note about podman update

### ISSUE THREAD

**Issue by cmoulliard** [containers/podman-desktop#7880]
### Is your enhancement related to a problem? Please describe

To get the release note about a podman upgrade (5.0.3 -> 5.1.1), it is needed to figure out what the url about the github repository is (= https://github.com/containers/podman) and to navigate next to the releases page: https://github.com/containers/podman/releases to find the content of the release note: 5.1.0, 5.1.1

### Describe the solution you'd like

I suggest to also add part of UI proposing to install the new podman version to include a link to its RELEASE note or for the developer to compare the releases as such: https://github.com/containers/podman/compare/v5.0.3...v5.1.1

### Describe alternatives you've considered

n/a

### Additional context

Screenshot of the section mentioning the podman upgrade:
![Screenshot 2024-07-02 at 09 12 51](https://github.com/containers/podman-desktop/assets/463790/80ac09a8-8c31-4be1-8630-2752e1aedcc5)

**Comment by axel7083** [comment]
@benoitf @deboer-tim the Provider[^1] interface have many similarity with the CLITool[^2] interface. 

**Provider**

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L605

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L621-L622

**CLITool**

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L4332-L4336

I am wondering if we should not make the Provider extend the CLITool. We were talking 

[^1]: https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L587
[^2]: https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L4320


During some discussion we mention that we might want to have the `podman` tool as a CLI Tool, we might want to make the Provider interface extend the CLI Tool ?

Reference issue https://github.com/containers/podman-desktop/issues/8003

**Comment by benoitf** [comment]
Provider should not reuse CliTool

**Comment by benoitf** [comment]
if podman extension wants to register 'podman' then it'll register a CliTool 'podman'

**Comment by deboer-tim** [comment]
+1. We need to be careful about overlap, but not every Provider is a CliTool and vice versa.

**Comment by axel7083** [comment]
> +1. We need to be careful about overlap, but not every Provider is a CliTool and vice versa.

Okey got it

**Comment by axel7083** [comment]
What would be the best solution here

For the `podman` extension, **we are not** using the `Octokit` package to get the latest update, we are using an hardcoded file (forcing us to update it btw)

https://github.com/containers/podman-desktop/blob/7793c58af0b8084bf504be1a0a5e11b5cca33467/extensions/podman/src/podman5.json#L1-L2

My first proposal would be to add a `changelog` property to the `ProviderUpdate` interface in the `extension-api`.

https://github.com/containers/podman-desktop/blob/86c7ee8b7dd09225a0b59dcfcf535021664bc48f/packages/extension-api/src/extension-api.d.ts#L543-L549

However, my question is: for the podman extension, _how do I get the changelog_, since we have a json file containing the latest version metadata, we do not rely on external connectivity to know if an update is available, so a simple change would to include the changelog in it.

The second solution would be to make a network call to get the release, but this would make it network needy.

Any opinion @benoitf @deboer-tim

**Comment by benoitf** [comment]
> For the podman extension, we are not using the Octokit package to get the latest update, we are using an hardcoded file (forcing us to update it btw)

I would avoid the small complaints hidden in parenthesis that are not unrelated to the topic.

The main reasons are :
- control the version being embedded in the product.
- be able to fetch the right version when building the airgapped distribution.
- not display new versions in Podman Desktop until it has been validated. People could have unexpected behaviors.

>The second solution would be to make a network call to get the release
here we need to handle the offline/air gapped mode so we can't use that way.

As the data are coming from the JSON file and the release being 
```
https://github.com/containers/podman/releases/tag/<tag>
```

in https://github.com/containers/podman-desktop/blob/main/extensions/podman/src/podman5.json we have the version

From podman extension the link would be `https://github.com/containers/podman/releases/tag/v${version}`


> My first proposal would be to add a changelog property to the ProviderUpdate interface in the extension-api.

Yes proposal looks good, I would just not call it 'changelog' but `releaseNotes` which looks more generic (and was the title of the issue) and of course it needs to be an optional field to handle backward support.

Might be required here to have a complex field for the releaseNotes like releaseNotes: {link?: string, content?: string}

Then, interesting topics:

- Display: How is it displayed to the user ? 
For now there is an 'update button', will it display two buttons, one for download, one for the release notes.
or is it displayed inline ?

- Airgapped mode. Some users are using the offline installer, and it means that in that case clicking on the link won't be possible (result won't be displayed)
@slemeur : Do we need to display the release notes of Podman even in a non-connected mode ? In that case, we would need to embed in the podman5.json the content of the release notes and use the optional field with the content rather than the link

**Comment by slemeur** [comment]
In general, I'd say yes. Users, in a disconnected or connected environment, when they are doing an upgrade, they would like to be informed about what the upgrade is bringing to them. 

The caveat, is that in a non-connected environment, I imagine the Podman Desktop upgrades could be managed by an IT department. There are less chances that the user will get "each" of the updates we are producing. As a result, the user might do an upgrade including the changes of multiple releases. 

I don't want to make this overly complicated, with a mechanism to display the changes from the past updates of podman, but it would be nice to point to where those information can be found (even if the restricted environment might not allow to access it). 

As to where displaying it... what would you think about adding a "What's new" section in the settings, where the user could find the information about all of the latest tools configured? When we proceed to an upgrade, we would then display a notification saying "Learn more about Podman version 5.x" and when the user clicks on it, it would display that page?

**Comment by axel7083** [comment]
> In general, I'd say yes. Users, in a disconnected or connected environment, when they are doing an upgrade, they would like to be informed about what the upgrade is bringing to them.

Yes, I think we all agree on this.

> As to where displaying it... what would you think about adding a "What's new" section in the settings

I think this is complicated as tools and providers (kubernetes/container) are managed by extensions, we would need a way for them to register those "news article" to let podman desktop displays them.

As an example we have JetBrain which have a `What's new` option in the help section

![image](https://github.com/user-attachments/assets/23e795dc-2e2e-49b5-b750-7c554c69387c)

![image](https://github.com/user-attachments/assets/7fc2ff83-991f-4c5b-9397-665b7aaecb52)

However, I have some issue imagining how this would scale with multiples tools, and how each extensions would register those news.

> When we proceed to an upgrade, we would then display a notification saying "Learn more about Podman version 5.x" and when the user clicks on it, it would display that page?

Maybe users will want to see the release note before doing the update ?

**Comment by deboer-tim** [comment]
I'm going to comment out of order. :)

> Maybe users will want to see the release note before doing the update ?

Personally I wouldn't expect or want to see the full release notes inside our UI before installing - but a very short description (a 'why upgrade?' or 'learn more') and link to the release note would be a nice touch.

> > As to where displaying it... what would you think about adding a "What's new" section in the settings

IMHO that's buried. I would prefer to see important upgrade recommendations or release notes on the dashboard, with a close button to make it disappear. This is what many tools like VS Code do.

> However, I have some issue imagining how this would scale with multiples tools, and how each extensions would register those news.

Yeah, that is an issue since we have providers, CLI tools, extensions, and Podman Desktop itself. I definitely wouldn't try to solve it for all of those now, and the UI/usability might be different (e.g. extensions are normally auto-update), maybe just a simple pattern that can work for both providers (based on how we already display the upgrade button) and PD.

**Comment by axel7083** [comment]
I tried looking a bit around to see how this could be integrated.

## External link in Provider banner

I first took a look at the JetBrain toolbox

![image](https://github.com/user-attachments/assets/37fed187-d975-4287-b258-bb1010c6042b)

And the _'why upgrade?' or 'learn more'_ suggested by @deboer-tim is provided by a `what's new`. When registering an update, we could add an optional field `releaseNote`, and add an external link inside the ProviderCard, this would scale for the each providers, while being minimalist. 

![image](https://github.com/user-attachments/assets/70f20efc-c32c-459f-a837-66a95b1c9358)

## Confirmation dialog

Another approach would be to let the extension manage the update, and while performing the install, it would display a confirmation dialog with a release note button.

![image](https://github.com/user-attachments/assets/1a02073f-48ec-4243-9661-7a03c411949f)

However we have some limitation, we cannot choose from the extension the orders of the buttons. Here I tried to write

```ts
window.showInformationMessage("Update to v9.8.7 ?", "Cancel", "Open release note", "Confirm");
```

but the _Open release note_ was placed at the end. 

cc @slemeur @benoitf

**Comment by benoitf** [comment]
I think both approaches works for me.

quick note

for 
![image](https://github.com/user-attachments/assets/eb46acd4-772b-4267-9dce-33d42d4d3eaa)

maybe we should not repeat twice the version (like only the `what's new in version name` and `Update'

But there is a 'dashboard revamp' so tiles will be displayed differently anyway
https://github.com/containers/podman-desktop/issues/4395

but we still need to have a way to notify the user

(so maybe for now start within the confirmation dialog as anyway you need to enhance the API to let a new field being added)
