### ISSUE TITLE
Migrate `StatusIcon` to the UI library 

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop#7899]
### Is your feature request related to a problem? Please describe

AI-Lab still has its own implementation of the StatusIcon component, and should uses the one from podman-desktop as it is just a copy 

### Describe the solution you'd like

Avoid https://github.com/containers/podman-desktop-extension-ai-lab/issues/1271

**Comment by deboer-tim** [comment]
+1, but as part of this we need to decide what we do about the 'list of statuses'. i.e. currently this icon supports most of the status colors in the palette but not all of them, and we have changed these as necessary since it is an internal component. Bootc also has copy, but it is not a direct copy since the names of the statuses are different.

So at a minimum, component needs to list somewhere which status strings it supports.

**Comment by deboer-tim** [comment]
> +1, but as part of this we need to decide what we do about the 'list of statuses'. i.e. currently this icon supports most of the status colors in the palette but not all of them, and we have changed these as necessary since it is an internal component. Bootc also has copy, but it is not a direct copy since the names of the statuses are different.
> 
> So at a minimum, component needs to list somewhere which status strings it supports.

I forgot there was a comment in StatusIcon that basically says 'I support these five states, anything else is just an outline'.. I don't love it and I don't think it's very obvious for an adopter (maybe should be some kind of enum at least?), but I guess that's ok to start.

**Comment by axel7083** [comment]
> So at a minimum, component needs to list somewhere which status strings it supports.

Yes I agree with that, we could add either `undefined` or `UNKNOWN` as supported, to make it just outline
