### ISSUE TITLE
Installation on Window 10 fails

### ISSUE THREAD

**Issue by gicat** [containers/podman-desktop#790]
### Bug description

Executing the _podman-desktop-0.9.1.exe_ on Windows the following dialog appears, but is not possible to click on the **'Ok'** button. After a few seconds the dialog disappears and the installation fails without other details.

![Screenshot 2022-11-08 170313](https://user-images.githubusercontent.com/2095385/200615010-06999d3d-17c8-4b2a-90eb-8ebcab1bbc73.png)

Sometimes the installation fails without displaying the dialog.

### Operating system

Microsoft Windows 10 Enterprise version: 10.0.19044

### Version

0.9.1

### Steps to reproduce

Launch _podman-desktop-0.9.1.exe_

**Comment by benoitf** [comment]
hi @gicat thanks for the report.
I'm not able to reproduce the issue :-(

Do you see the window of Podman Desktop as well below the dialog box ? or you just have this popup ?

> the installation fails without other details.

Is that some application is killing the process ? Also at this step there is no 'installation' step you should see the dashboard of Podman Desktop

**Comment by gicat** [comment]
Hi @benoitf thanks for your feedback.
I only see the dialog box, it is not possible to interact with it. It briefly appears on notification area. In fact something appens in notification area, see the image below. The application is not installed.
![image](https://user-images.githubusercontent.com/2095385/200801913-14ec37ad-1045-42b0-ad76-80bfd68c2231.png)

I have Kaspersky as antivirus, the only application that can kill the process I think, but I do not receive any alert from the antivirus.

**Comment by cdrage** [comment]
@gicat You **may** be hitting this bug: https://github.com/containers/podman-desktop/issues/700

Can you uninstall and try reinstalling again and see if Kaspersky removes the file? It's unfortunately marking Podman Desktop as a false positive despite us having signed Windows binaries. 

If it does, please submit a false positive under your client (https://forum.kaspersky.com/topic/kaspersky-how-to-report-false-positive-22328/) in order to help us remove the entry from the Kaspersky database.

**Comment by gicat** [comment]
@cdrage  I can confirm that is Kaspersky the problem. I will submit a false positive to your suggested url.

Thank you.
Regards,
Giuseppe
