### ISSUE TITLE
Odd right spacing on terminal for push image

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8078]
### Bug description

![Screenshot 2024-07-15 at 10 45 32 AM](https://github.com/user-attachments/assets/78acae76-c40c-4580-9501-982b91d929f8)

There's a weird misalignment / white spacing on the right with "Push Image"

### Operating system

mac M1

### Installation Method

None

### Version

1.11.1

**Comment by SoniaSandler** [comment]
@cdrage It looks like it's the scroll bar area, but since there is nothing in the terminal, the scroll bar is not available/enabled.
I tried looking for a solution like `y-overflow: auto`, but since it's an Xterm terminal, I'm not sure it's possible. Another possible solution is to remove the scroll bar, but if there are logs, I think it is important for the user to be able to scroll in the terminal.
This is what I get on Linux, so it might just be the style of the scroll bar.:


![Image](https://github.com/user-attachments/assets/3e5e365e-faae-4f85-9c98-67ee42eb818f)



![Image](https://github.com/user-attachments/assets/65d33ba0-2578-4d2f-9838-fd30ae9ac439)



![Image](https://github.com/user-attachments/assets/deffe4e9-2292-4329-9895-216b8cd8a8bf)

**Comment by deboer-tim** [comment]
The double scrollbar is unfortunate - can we disable it/allow it full height and only use the dialog scrollbar?

**Comment by SoniaSandler** [comment]
@deboer-tim I'm pretty sure there is a way to disable the terminal scrollbar, and I'll check about the full height option

**Comment by SoniaSandler** [comment]
@deboer-tim it looks like the only way to remove the terminal's scroll bar is to disable it manually in Xterm's css file in `node_modules` https://github.com/xtermjs/xterm.js/issues/3074. To fix the double scrollbar problem, we could remove the outer one, and adjust the window's height to fit its content and leave the terminal scrollbar. However, this option will still leave the weird spacing (and it will differ in each OS as seen in the screenshots) , but the theme of PD and the terminal could also impact its visibility/significance


![Image](https://github.com/user-attachments/assets/af7e3e86-e79b-4335-8ff7-db3b04360e64)

**Comment by SoniaSandler** [comment]
Happens again following the merge of https://github.com/containers/podman-desktop/pull/8413
