### ISSUE TITLE
Podman installation error not readable on windows

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#809]
### Is your enhancement related to a problem? Please describe

podman refuses to install but hard to guess why

### Describe the solution you'd like

Better log view

### Additional context

![image](https://user-images.githubusercontent.com/695993/201115037-65cbe310-3ebb-44ad-a73d-138703ca1638.png)

**Comment by gbraad** [comment]
sounds like an issue in the log writer in the dialog. The podman installation writes the progress with runes (removes text fragments to show a progress indicator). The escape code `[1A[J` removes the line and rewrites. Is there some functionality inside Podman Desktop/Node to handle this behaviour before writing it to the dialog? Is it otherwise possible to omit a large part and only report the last 10 lines?
