### ISSUE TITLE
Add a guides section to the website 

### ISSUE THREAD

**Issue by myfear** [containers/podman-desktop#8256]
### Is your enhancement related to a problem? Please describe

I really want to learn more in depth about features that cover topics instead of individual product features. 

### Describe the solution you'd like

I'd love to have a guides section on the website. Something almost tutorial like that gives a 101 hands on experience to start working with containers, pods, kubernetes, databases, etc.
All in one place on the website. 

@deboer-tim wouls you be able to give me some hints to make docusaurus do this?
My understanding is that it handles everything under /docs right now but I wouldn't want this to be under /docs/guides but more a separate top level navigation /guides.

Thanks,
M

- [x] https://github.com/containers/podman-desktop/issues/8868

- [x] https://github.com/containers/podman-desktop/issues/8869

- [x] https://github.com/containers/podman-desktop/issues/8870

- [x] https://github.com/containers/podman-desktop/issues/8871

- [x] https://github.com/containers/podman-desktop/issues/8872

_No response_

**Comment by cdrage** [comment]
@shipsing See the code in docusaurus how we do it with blog posts.

We could add a new button on the top that links to guides, and have it similar to blog posts where it's a "separate" section of the site where we can categorize each doc / add to it.

**Comment by shipsing** [comment]
Thank you @cdrage for the above information.I think this issue covers two aspects:

- One related to the presentation or placement as separate top level navigation section
- Other related to the content that we will cover in that section. The ask is to have a tutorial-like section that gives a 101 hands-on experience to start working with containers, pods, kubernetes, databases, etc.

We need to dig deeper from content perspective:

- What are the aspects that we want to cover in this separate tutorial section that are not part of our existing documentation? Is it more conceptual or end-to-end procedural task workflow information that we want to cover?

- Having a tutorial section is a separate content type. We would need to cover example configurations (YAML snippets to create a container or kube object) as well for user's reference. A tutorial is designed to help users to quickly complete a particular task with minimal specified requirements. For this, we also need to identify some common use cases for our application users, for example, deploying and running a container or deploying and running a Kubernetes cluster. All the tasks that are part of the use case or any other aspect to be kept in mind, we need to cover all of them to make the user journey complete. What are those common use cases for Podman Desktop?

- We need to think from maintenance perspective as well so that the configuration examples remain in up-to-date state. Because once we start providing procedural details for an end-to-end use case, we might need to include several config examples, which are ready to use for our users.

I will add this issue to our Thursday's call for discussion, @slemeur.

**Comment by shipsing** [comment]
[Analysis document](https://docs.google.com/document/d/1SXIq-P43dmXVp1CX-Q5FgRTNECP07p_1WPACmnLUIO0/edit) for this issue. Started working on creating the tutorial section.

**Comment by shipsing** [comment]
- [ ] Add a tutorial - Running a pod using a container or docker file
- [ ] Add a tutorial - Running a Kubernetes cluster
- [ ] Add a tutorial - Managing your development resources
- [ ] Add a tutorial: Interacting with databases from the Podman Desktop application
- [ ] Add a tutorial: Running an AI application
