### ISSUE TITLE
Building an image with different context folder selected is broken

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop#8460]
### Bug description

I was trying to build an image using containerfile mentioned in README of the sso extension.

I got: `.../build/oolbox.containerfile: no such file or directory` during the build. It seems that building the image is missing a letter. I assume that the problem is on podman-desktop side.

![Screenshot_20240809_173829](https://github.com/user-attachments/assets/b2408194-f8c3-4644-b090-dd23e6855ea3)

### Operating system

Mac OS 14 M2

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

1. Open Build an image page
2. choose a containerfile to build
3. Change the context folder location to something else
4. Build an image
5. Assert: Image is successfully built
Actual result: There is an error during the build: `.../build/oolbox.containerfile: no such file or directory`

### Additional context

Issue was opened on sso side before: https://github.com/redhat-developer/podman-desktop-redhat-account-ext/issues/233

**Comment by deboer-tim** [comment]
FWIW I had taken a quick initial look - the UI looks ok and context is being passed to Podman (log shows the passed context), but fails in UI and appears to work ok via cli.

**Comment by SoniaSandler** [comment]
@deboer-tim is it possible to have a containerfile outside the build context?
At first I thought the problem was with getting the relative path for the containerfile because of the way the name of the file was missing its few first letters, but after fixing it, I still got the same error. 
In `Dockerode`'s documentation, it says `Context: provides the path to the Dockerfile...`.
I also looked at `buildImage` in `container-registry.ts` and saw that we don't specify `options?.containerFile` anywhere in the `buildOptions` that we pass to `matchingContainerProviderApi.buildImage`, and after fixing, `buildImage` still doesn't work for containerfiles outside the build context

**Comment by deboer-tim** [comment]
From the command line the container file and folder don't need to be relative, e.g. `podman build -f Containerfile.in $HOME` (https://docs.podman.io/en/latest/markdown/podman-build.1.html), and I just verified again that seems to be fine. I was assuming this would be fine via api too, but I haven't had a chance to try your PR yet.

**Comment by SoniaSandler** [comment]
@deboer-tim I think using a containerFile outside the context folder is not supported by `Dockerode`'s `buildImage`. It looks like https://github.com/apocas/dockerode/issues/762 is referencing a similar problem to the one we have here. 
I've tried using the `{context: 'some-dir', src: ['containerFile-path']}` option instead of using tar, but I got  `docker "../file1.Containerfile" is outside of "/var/tmp/libpod_builder2823748288/build"` for containerFile relative path or `no such file <dirpath>/<full file path>` (double dir path) for absolute containerFile path.
It looks like `Dockerode` also uses `tar.pack` for the `{context, src}` option, so I assume the containerFile needs to be in the tar folder for `buildImage` to work.

**Comment by benoitf** [comment]
@SoniaSandler did you compare what is being sent to the socket using dockerode or using the docker and podman CLI ?

**Comment by SoniaSandler** [comment]
@benoitf in both the Podman and Docker CLI, I'm able to build images using Containerfiles that are outside the build context.
I'm not sure how to check what is being sent to the socket

**Comment by feloy** [comment]
In `packages/renderer/src/lib/image/BuildImageFromContainerfile.svelte`:
```
    const relativeContainerfilePath = containerFilePath.substring(containerBuildContextDirectory.length + 1);
```

The frontend expects that the Containerfile selected by the user is somewhere in the context, which is not necessary the case.

If I understand correctly, buildImage expects to get the Containerfile path relative to the context, meaning that this should be replaced by computing the path of the Containerfile relative to the context dir.

**Comment by SoniaSandler** [comment]
@feloy you are right, that was part of the problem. However, even after fixing the relative path, I still got an error `docker "../file1.Containerfile" is outside of "/var/tmp/libpod_builder2823748288/build` when trying to include a containerfile from outside the context. I found an existing issue in dockerode's repository (a few replies above this one). I think it is related to the fact that dockerode uses tar to package the context, and I don't think it is possible to include a file outside the directory inside a tar
