### ISSUE TITLE
podman connection vmtype should not be used to store label and user friendly information

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman-desktop#8484]
https://github.com/containers/podman-desktop/blob/93efec446f2f210744efa4ccdec4ba2f81e748de/extensions/podman/src/extension.ts#L803

**Comment by afbjorklund** [comment]
It seems to be missing qemu, but I guess it will fall back to "qemu"

```typestring
    default:
      return provider;
```

**Comment by axel7083** [comment]
We could simply remove the `getProviderLabel`.

**Comment by axel7083** [comment]
The same is happening for the machine name: 

https://github.com/containers/podman-desktop/blob/93efec446f2f210744efa4ccdec4ba2f81e748de/extensions/podman/src/extension.ts#L796-L796

We are not providing the right value.

**Comment by axel7083** [comment]
cc @slemeur @benoitf is it a requirement to have the following labels

https://github.com/containers/podman-desktop/blob/93efec446f2f210744efa4ccdec4ba2f81e748de/extensions/podman/src/util.ts#L162-L163

Because currently, if we remove those hardcoded label and use the right value, we will get the following change

| before | after |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/41e78b57-dffb-4563-88c5-a10ee54f62c8) | ![image](https://github.com/user-attachments/assets/a581a9d1-5fa2-44dc-a470-0a5ebcadba1c)
| ![image](https://github.com/user-attachments/assets/d534cbce-1c61-4255-8c84-a8700dcab3ed) | ![image](https://github.com/user-attachments/assets/7cb1ef20-aed2-47a3-b550-72b78647b2a8) |


Currently extensions registering providers (E.g. podman) do not have a way of providing a label, if we want to keep this _friendly_ labels we would have to make an api change (adding an optional field probably).

Any opinions ?

**Comment by jeffmaury** [comment]
I'm fine with the optional field

**Comment by axel7083** [comment]
After discussing with @benoitf 

There is a consensus on having optional field to provide labels `displayName` (or better name for property) to improve readability for user
