### ISSUE TITLE
Unable to view dev tools for extensions with router.mode.memory()

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop#8752]
### Bug description

With the https://github.com/containers/podman-desktop/pull/8489 change, we are now unable to view the dev console for extensions when right-clicking:

![Screenshot 2024-09-04 at 10 44 51 AM](https://github.com/user-attachments/assets/bf8a5629-d022-4a30-aa1e-28ef98049176)

Changing this bash to `hash()` works however.

### Operating system

mac m1

### Installation Method

None

### Version

1.11.1

**Comment by benoitf** [comment]
cc @dgolovin

**Comment by feloy** [comment]
As a workaround, this command can be used from the console of the main devtools (when the webview is opened):

```
document.querySelector('webview').openDevTools();
```

**Comment by dgolovin** [comment]
The problem is because these two conditions always return false
* https://github.com/containers/podman-desktop/blob/0ad301cddcdb33c0ca334922c68d53183f46149e/packages/main/src/mainWindow.ts#L202
* https://github.com/containers/podman-desktop/blob/0ad301cddcdb33c0ca334922c68d53183f46149e/packages/main/src/mainWindow.ts#L217

because `parameters.pageURL` for memory mode equals development server's root URL.

Simple fix is to remove pageURL check. It means if you request DevTools without webview loaded nothing would happen, but if you do that when vebview is loaded DevTools window will show up.

Another fix is to use hash navigation for development mode and memory for production, but I did not check how to identify reliably for DEV/PROD mode on renderer side.

More complicated check would be, if possibe, to check if extension is loaded instead on pageURL.

Considering it is show only in dev mode when running `pnpm watch` I would go for simple fix and remove pageURL check.

@benoitf @cdrage WDYT?
