### ISSUE TITLE
The default way users create containers is from images, I would argue the only way.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-desktop#959]
### Bug description

Therefore you should preselect the image selection rather then Contanerfile (Also switch the order, since image should come first).

### Operating system

linux

### Version

0.10.0

**Comment by deboer-tim** [comment]
This is for the Create Container dialog? I am wondering if we should remove the button entirely, since you can do this directly from the Image page. As a user that's where I'm used to going anyway, and if some users haven't made the connection then a link in the description (e.g. "Create new containers via Images") would suffice.
