### ISSUE TITLE
Deleting Kind resource from Resource Page breaks Podman Desktop navigation, hard kill and restart required

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop#9717]
### Bug description

User is unable to navigate Podman Desktop unless it's restarted

### Operating system

Windows 10 22H2 WSL

### Installation Method

Installer from website/GitHub releases

### Version

1.14.0

### Steps to reproduce

* Create a Kind cluster
* After creation go back to Resources page
* Open Kind Cluster resource details
* Stop the cluster
* Delete the cluster
* Attempt to navigate anywhere

### Relevant log output

N/A

### Additional context

https://github.com/user-attachments/assets/292e75f6-3522-4173-91fa-79d28f1f530a

**Comment by ScrewTSW** [comment]
I tried Open Shift, unable to reproduce there, but @odockal reported seeing this bug before in a different resource page, more testing may be required

**Comment by odockal** [comment]
Encountered again today on Mac OS when deleting Kind from details page. Seems like affecting only Kind resource.

**Comment by axel7083** [comment]
Detailed explanation

Inside `PreferencesKubernetesConnectionRendering.svelte` and `PreferencesContainerConnectionRendering.svelte` we share some code. Precisely the following 

https://github.com/containers/podman-desktop/blob/9e8aad114dde4ad02cb012cd144a4b2848fae247/packages/renderer/src/lib/preferences/PreferencesContainerConnectionRendering.svelte#L58-L61

We are calling ` detailsPage.close();`, however bad news, detailsPage is nullable because it is a binding, here is the code leading to the nullable

https://github.com/containers/podman-desktop/blob/9e8aad114dde4ad02cb012cd144a4b2848fae247/packages/renderer/src/lib/preferences/PreferencesContainerConnectionRendering.svelte#L139-L140

We can clearly see that we have nullable binding, since the DetailsPage is only displayed... when we have the connectionInfo defined. Therefore we have a problem.

## Solution proposal

Remove the `detailsPage.close()` and replace it with a handleNavigation({ page: NavigationPage.RESOURCES, });
